import React,{useContext,useEffect,useRef,useState}from'react';
import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{useLocalSearchParams,useRouter}from'expo-router';
import{AuthContext}from'../context/AuthContext';
import expoconfig from'../expoconfig';

export default function TeacherLesson(){const{lessonId}=useLocalSearchParams();const{user}=useContext(AuthContext);const router=useRouter();const[lesson,setLesson]=useState<any>(null);const[answers,setAnswers]=useState<string[]>([]);const[result,setResult]=useState<any>(null);const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);const[seconds,setSeconds]=useState<number|null>(null);const submitted=useRef(false);
 useEffect(()=>{if(!user?.email||!user.portalSessionToken)return;fetch(`${expoconfig.API_URL}/api/student/lessons/${encodeURIComponent(String(lessonId))}?email=${encodeURIComponent(user.email)}`,{headers:{'X-Student-Token':user.portalSessionToken}}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(data=>{setLesson(data);setAnswers(Array(data.quiz?.length||0).fill(''));setSeconds(data.quizTimerSeconds??null)}).catch(e=>setResult({error:e.message||'Lesson could not be loaded.'})).finally(()=>setLoading(false))},[lessonId,user?.email,user?.portalSessionToken]);
 const submit=async()=>{if(submitted.current||!lesson?.quiz?.length||!user?.email||!user.portalSessionToken)return;submitted.current=true;setSubmitting(true);try{const r=await fetch(`${expoconfig.API_URL}/api/student/lessons/${encodeURIComponent(String(lessonId))}/submit`,{method:'POST',headers:{'Content-Type':'application/json','X-Student-Token':user.portalSessionToken},body:JSON.stringify({email:user.email,answers})});if(!r.ok)throw new Error(await r.text());setResult(await r.json())}catch(e){submitted.current=false;setResult({error:e instanceof Error?e.message:'Quiz could not be submitted.'})}finally{setSubmitting(false)}};
 useEffect(()=>{if(seconds==null||result||loading)return;if(seconds<=0){void submit();return}const timer=setTimeout(()=>setSeconds(v=>v==null?null:v-1),1000);return()=>clearTimeout(timer)},[seconds,result,loading]);
 if(loading)return <SafeAreaView style={s.loading}><ActivityIndicator color="#7B2FC0"/><Text>Opening your lesson…</Text></SafeAreaView>;
 if(!lesson)return <SafeAreaView style={s.loading}><Text>{result?.error||'Lesson unavailable.'}</Text><Pressable onPress={()=>router.back()}><Text>Go back</Text></Pressable></SafeAreaView>;
 return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={s.content}><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={20} color="#472651"/></Pressable><View style={s.headerCopy}><Text style={s.eyebrow}>{lesson.lesson_type} · FROM YOUR TEACHER</Text><Text style={s.title}>{lesson.lesson_title}</Text><Text style={s.description}>{lesson.lesson_description}</Text></View><View style={s.bookIcon}><Ionicons name="book" size={22} color="#7B2FC0"/></View></View>
  <View style={s.progress}><Text>{lesson.sections?.length||0} lesson cards</Text>{lesson.quiz?.length>0&&<Text>{lesson.quiz.length} question quiz</Text>}</View>
  {lesson.sections?.map((section:any,index:number)=><View style={s.card} key={index}><View style={s.cardNumber}><Text>{String(index+1).padStart(2,'0')}</Text></View><Text style={s.cardTitle}>{section.heading}</Text><Text style={s.cardBody}>{section.body}</Text></View>)}
  {lesson.quiz?.length>0&&<View style={s.quiz}><View style={s.quizHead}><View><Text style={s.quizEyebrow}>KNOWLEDGE CHECK</Text><Text style={s.quizTitle}>Show what you learned</Text></View>{seconds!=null&&!result&&<View style={s.timer}><Ionicons name="time-outline" size={16} color="#7B2FC0"/><Text>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</Text></View>}</View>
   {!result&&lesson.quiz.map((q:any,index:number)=><View style={s.question} key={index}><Text style={s.questionCount}>QUESTION {index+1}</Text><Text style={s.prompt}>{q.prompt}</Text>{(q.type==='MULTIPLE_CHOICE'||q.type==='TRUE_FALSE')?<View style={s.choices}>{q.choices.map((choice:string)=><Pressable key={choice} style={[s.choice,answers[index]===choice&&s.choiceSelected]} onPress={()=>setAnswers(items=>items.map((a,i)=>i===index?choice:a))}><Text style={[s.choiceText,answers[index]===choice&&s.choiceTextSelected]}>{choice}</Text><Ionicons name={answers[index]===choice?'checkmark-circle':'ellipse-outline'} size={18} color={answers[index]===choice?'#7B2FC0':'#BBAFC0'}/></Pressable>)}</View>:<TextInput style={s.answer} value={answers[index]} onChangeText={value=>setAnswers(items=>items.map((a,i)=>i===index?value:a))} placeholder="Type your answer"/>}</View>)}
   {!result&&<Pressable style={[s.submit,submitting&&{opacity:.6}]} disabled={submitting} onPress={()=>void submit()}><Text style={s.submitText}>{submitting?'Checking…':'Submit quiz'}</Text><Ionicons name="arrow-forward" size={17} color="#fff"/></Pressable>}
   {result&&<View style={s.result}><Ionicons name={result.error?'alert-circle':'trophy'} size={34} color={result.error?'#C65A6C':'#75A849'}/><Text style={s.resultTitle}>{result.error?'Quiz could not be saved':`${result.percentage}%`}</Text><Text style={s.resultText}>{result.error||`You answered ${result.score} of ${result.maxScore} questions correctly. Your teacher can now see this attempt.`}</Text><Pressable style={s.done} onPress={()=>router.replace('/LearnMenu')}><Text style={s.doneText}>Back to learning path</Text></Pressable></View>}
  </View>}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8F4FB'},content:{padding:20,paddingBottom:45,maxWidth:760,width:'100%',alignSelf:'center'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12,backgroundColor:'#FAF7FC'},header:{flexDirection:'row',alignItems:'flex-start',gap:13,padding:20,borderRadius:23,backgroundColor:'#fff'},back:{width:42,height:42,borderRadius:13,backgroundColor:'#F3EBF8',alignItems:'center',justifyContent:'center'},headerCopy:{flex:1},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#72A349'},title:{fontFamily:'Jua',fontSize:25,color:'#42274D',marginTop:5},description:{fontSize:11,color:'#8D7E94',lineHeight:17,marginTop:4},bookIcon:{width:42,height:42,borderRadius:13,backgroundColor:'#EFE3F8',alignItems:'center',justifyContent:'center'},progress:{flexDirection:'row',gap:8,marginVertical:14},card:{padding:21,borderRadius:20,backgroundColor:'#fff',marginBottom:12},cardNumber:{width:34,height:27,borderRadius:9,backgroundColor:'#EFE4F8',alignItems:'center',justifyContent:'center'},cardTitle:{fontFamily:'Jua',fontSize:18,color:'#462950',marginTop:13},cardBody:{fontSize:13,color:'#75687B',lineHeight:21,marginTop:7},quiz:{padding:20,borderRadius:22,backgroundColor:'#fff',marginTop:8},quizHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},quizEyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#71A148'},quizTitle:{fontFamily:'Jua',fontSize:20,color:'#43274D',marginTop:4},timer:{flexDirection:'row',gap:5,alignItems:'center',padding:9,borderRadius:10,backgroundColor:'#F0E5F8'},question:{paddingVertical:18,borderBottomWidth:1,borderBottomColor:'#EEE6F1'},questionCount:{fontSize:8,fontWeight:'900',letterSpacing:1,color:'#8D66A2'},prompt:{fontSize:14,fontWeight:'700',color:'#46304F',marginTop:7,lineHeight:20},choices:{gap:8,marginTop:12},choice:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:13,borderWidth:1,borderColor:'#E5DBEA',borderRadius:13},choiceSelected:{borderColor:'#9B60C6',backgroundColor:'#F6EEFC'},choiceText:{fontSize:12,color:'#705F77'},choiceTextSelected:{fontWeight:'800',color:'#65258E'},answer:{marginTop:12,borderWidth:1,borderColor:'#DED3E4',borderRadius:12,padding:13,color:'#3F2948'},submit:{marginTop:20,height:50,borderRadius:14,backgroundColor:'#7B2FC0',flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},submitText:{color:'#fff',fontWeight:'800'},result:{alignItems:'center',padding:25},resultTitle:{fontFamily:'Jua',fontSize:27,color:'#42274D',marginTop:9},resultText:{textAlign:'center',color:'#83748A',fontSize:11,lineHeight:17,marginTop:5},done:{marginTop:17,padding:13,borderRadius:12,backgroundColor:'#F0E5F8'},doneText:{color:'#6E3295',fontWeight:'800'}});
