import { Ionicons } from '@expo/vector-icons';
import { AudioManager, AudioRecorder, FileFormat, FilePreset } from 'react-native-audio-api';
import { router } from 'expo-router';
import React, { useContext, useEffect, useMemo, useRef, useState } from 'react';
import { Image, ImageBackground, Pressable, SafeAreaView, Text, View } from 'react-native';
import BackIcon from '../assets/svg/back-icon.svg';
import { AuthContext } from '../context/AuthContext';
import expoconfig from '../expoconfig';
import styles from '../styles/stylesQuackTalkPracticeRoom';
import { GeminiGuidedPhraseLive, GuidedLiveAccess, GuidedPhraseTurn, MeaningEvaluation } from '../services/guidedPhraseLive';

const bg=require('../assets/quacktalk/guided-phrase-studio-v1.png');
const idle=require('../assets/img/Sumi_PoseB_WinterUni_Smile.png');
const blink=require('../assets/img/Sumi_PoseB_WinterUni_EyesClosed_Smile.png');
const open=require('../assets/img/Sumi_PoseB_WinterUni_Open.png');
const openBlink=require('../assets/img/Sumi_PoseB_WinterUni_EyesClosed_Open.png');
type AzureScores={recognizedText:string;pronunciation:number;accuracy:number;fluency:number;completeness:number};

export default function GuidedPhraseLiveRoom(){
 const {user}=useContext(AuthContext);const recorderRef=useRef<AudioRecorder|null>(null);const liveRef=useRef<GeminiGuidedPhraseLive|null>(null);const heartbeat=useRef<ReturnType<typeof setInterval>|null>(null);const blinkTimer=useRef<ReturnType<typeof setInterval>|null>(null);const startedAt=useRef(Date.now());
 const [state,setState]=useState<'connecting'|'ready'|'listening'|'thinking'|'speaking'|'finished'|'error'>('connecting');const [message,setMessage]=useState('Connecting Sumi…');const [turn,setTurn]=useState<GuidedPhraseTurn|null>(null);const [turns,setTurns]=useState(0);const [remaining,setRemaining]=useState(1200);const [blinked,setBlinked]=useState(false);const [mouth,setMouth]=useState(false);const [azure,setAzure]=useState<AzureScores[]>([]);const [evaluations,setEvaluations]=useState<MeaningEvaluation[]>([]);const [sumiText,setSumiText]=useState('');const [heard,setHeard]=useState('');
 const frame=state==='speaking'?(blinked?openBlink:mouth?open:idle):(blinked?blink:idle);const average=useMemo(()=>{const values=azure.map(x=>(x.pronunciation+x.accuracy+x.fluency+x.completeness)/4);const speech=values.length?values.reduce((a,b)=>a+b,0)/values.length:0;const context=evaluations.length?evaluations.reduce((a,b)=>a+b.contextScore,0)/evaluations.length:0;return Math.round((speech+context)/2);},[azure,evaluations]);

 useEffect(()=>{blinkTimer.current=setInterval(()=>{setBlinked(true);setTimeout(()=>setBlinked(false),150);},3400);return()=>{if(blinkTimer.current)clearInterval(blinkTimer.current);};},[]);
 useEffect(()=>{if(state!=='speaking'){setMouth(false);return;}const id=setInterval(()=>setMouth(v=>!v),170);return()=>clearInterval(id);},[state]);
 useEffect(()=>{if(!user?.email){setState('error');setMessage('Sign in to start Guided Phrase Practice.');return;}let active=true;
  const start=async()=>{try{const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/live-token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,scenario:'First conversations in Japan'})});const body=await response.json();if(!response.ok)throw new Error(body.message||'Guided Phrase could not start.');if(!active)return;setRemaining(body.remainingSeconds);const live=new GeminiGuidedPhraseLive({onConnected:()=>{setState('ready');setMessage('Sumi is ready.');},onSpeaking:value=>{if(value){setState('speaking');setMessage('Sumi is speaking…');}else setState(s=>s==='listening'||s==='finished'?s:'ready');},onInputTranscript:text=>setHeard(text),onOutputTranscript:text=>setSumiText(previous=>previous+text),onTurn:value=>{setTurn(value);setTurns(current=>Math.min(5,current+1));setSumiText('');},onEvaluation:value=>setEvaluations(current=>[...current,value]),onError:text=>{setState('error');setMessage(text);},onComplete:()=>void finish()});liveRef.current=live;await live.connect(body as GuidedLiveAccess);
    heartbeat.current=setInterval(()=>void reportUsage(15),15000);
  }catch(error){setState('error');setMessage(error instanceof Error?error.message:'Guided Phrase could not start.');}};void start();return()=>{active=false;if(heartbeat.current)clearInterval(heartbeat.current);liveRef.current?.close();void recorderRef.current?.stop();};},[user?.email]);
 const reportUsage=async(seconds:number)=>{if(!user?.email)return;try{const r=await fetch(`${expoconfig.API_URL}/api/guided-phrase/usage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,seconds})});if(r.ok){const b=await r.json();setRemaining(b.remainingSeconds);if(b.remainingSeconds<=0)await finish();}}catch{}}
 const toggleMic=async()=>{if(state==='listening'){await stopMic();return;}if(!turn||state==='connecting'||state==='speaking'||state==='finished')return;try{const permission=await AudioManager.requestRecordingPermissions();if(permission!=='Granted')throw new Error('Microphone permission is required.');await AudioManager.setAudioSessionActivity(true);const recorder=new AudioRecorder();recorder.enableFileOutput({format:FileFormat.Wav,preset:FilePreset.Medium});recorder.onAudioReady({sampleRate:16000,bufferLength:1600,channelCount:1},({buffer})=>liveRef.current?.sendPcm16(buffer.getChannelData(0)));recorderRef.current=recorder;liveRef.current?.interrupt();const result=await recorder.start();if(result.status==='error')throw new Error(result.message);setHeard('');setState('listening');setMessage('Listening—speak your answer, then tap again.');}catch(error){setState('error');setMessage(error instanceof Error?error.message:'The microphone could not start.');}}
 const stopMic=async()=>{const recorder=recorderRef.current;if(!recorder)return;recorderRef.current=null;recorder.clearOnAudioReady();const result=await recorder.stop();liveRef.current?.endUserAudio();await AudioManager.setAudioSessionActivity(false);setState('thinking');setMessage('Sumi and Azure are reviewing your answer…');if(result.status==='success'&&result.paths[0]&&turn)void assess(result.paths[0],turn.targetJapanese);}
 const assess=async(path:string,reference:string)=>{try{const form=new FormData();form.append('audio',{uri:path.startsWith('file:')?path:`file://${path}`,name:'guided-turn.wav',type:'audio/wav'} as any);const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/assess?referenceText=${encodeURIComponent(reference)}`,{method:'POST',body:form});const body=await response.json();if(response.ok)setAzure(current=>[...current,body]);}catch{}finally{setState('ready');}}
 const finish=async()=>{if(state==='finished')return;setState('finished');setMessage('Five guided responses complete. Your feedback is ready.');if(heartbeat.current)clearInterval(heartbeat.current);liveRef.current?.close();if(user?.email)await fetch(`${expoconfig.API_URL}/api/guided-phrase/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,name:`${user.fname??''} ${user.lname??''}`.trim(),durationSeconds:Math.max(1,Math.round((Date.now()-startedAt.current)/1000)),score:average})}).catch(()=>undefined);}
 const leave=async()=>{if(state!=='finished'&&(azure.length||turns))await finish();router.replace('/QuackTalk');};
 useEffect(()=>{if(evaluations.length>=5&&azure.length>=5&&state!=='finished'){const id=setTimeout(()=>void finish(),1800);return()=>clearTimeout(id);}},[evaluations.length,azure.length,state]);
 return <SafeAreaView style={styles.safeArea}><ImageBackground source={bg} style={[styles.background,{backgroundColor:'#171934'}]} imageStyle={styles.backgroundArtwork} resizeMode="cover"><View style={[styles.sceneTint,styles.studioTint]}/><View style={styles.header}><Pressable onPress={()=>void leave()} style={styles.headerButton}><BackIcon width={18} height={18} fill="#47295A"/></Pressable><View style={[styles.headerMark,{backgroundColor:'#FCE9F1'}]}><Ionicons name="mic" size={18} color="#D84F83"/></View><View style={styles.headerCopy}><Text style={[styles.headerEyebrow,{color:'#D84F83'}]}>VOICE STUDIO · {turns}/5</Text><Text style={styles.headerTitle}>Guided Phrase</Text></View><View style={styles.timerPill}><Text style={styles.timerText}>{Math.ceil(remaining/60)}m</Text></View></View><View style={styles.stage}><View style={styles.coachStatus}><View style={styles.onlineDot}/><View><Text style={styles.coachStatusText}>GEMINI LIVE + AZURE</Text><Text style={styles.coachStatusSubtext}>{state.toUpperCase()}</Text></View></View><Image source={frame} style={styles.sumi} resizeMode="contain"/><View style={[styles.controlPanel,{paddingBottom:16}]}><View style={styles.promptRow}><View style={[styles.promptIcon,{backgroundColor:'#FCE9F1'}]}><Ionicons name="chatbubble-ellipses" size={20} color="#D84F83"/></View><View style={styles.promptCopy}><Text style={[styles.promptLabel,{color:'#D84F83'}]}>{state==='finished'?'SESSION COMPLETE':turn?`PRACTICE ${turns} OF 5`:'SUMI IS OPENING THE SESSION'}</Text><Text style={styles.promptTitle}>{turn?.learnerInstruction||sumiText||message}</Text>{turn&&<Text style={styles.promptNote}>{turn.englishMeaning}</Text>}{heard?<Text style={styles.promptNote}>Heard: {heard}</Text>:null}</View></View><View style={styles.microphoneArea}><Pressable disabled={!turn||state==='speaking'||state==='connecting'||state==='finished'} onPress={()=>void toggleMic()} style={({pressed})=>[styles.microphoneButton,{backgroundColor:state==='listening'?'#E34F6C':'#D84F83'},pressed&&styles.microphonePressed]}><Ionicons name={state==='listening'?'stop':'mic'} size={26} color="#fff"/></Pressable><Text style={styles.microphoneStatus}>{message}</Text></View>{state==='finished'&&<Pressable onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})} style={[styles.tutorialDone,{backgroundColor:'#D84F83'}]}><Text style={styles.tutorialDoneText}>View guided feedback</Text></Pressable>}</View></View></ImageBackground></SafeAreaView>;
}
