import { Ionicons } from '@expo/vector-icons';
import { AudioManager, AudioRecorder, FileFormat, FilePreset } from 'react-native-audio-api';
import { router } from 'expo-router';
import React, { useContext, useEffect, useRef, useState } from 'react';
import { Image, ImageBackground, Linking, Modal, Platform, Pressable, SafeAreaView, Text, View } from 'react-native';
import BackIcon from '../assets/svg/back-icon.svg';
import { AuthContext } from '../context/AuthContext';
import expoconfig from '../expoconfig';
import styles from '../styles/stylesQuackTalkPracticeRoom';
import { GeminiGuidedPhraseLive, GuidedLiveAccess, GuidedPhraseTurn, MeaningEvaluation } from '../services/guidedPhraseLive';

const bg=require('../assets/quacktalk/guided-phrase-studio-v1.png');
const idle=require('../assets/img/Sumi_PoseB_WinterUni_Smile.png');
const blink=require('../assets/img/Sumi_PoseB_WinterUni_EyesClosed_Smile.png');
const open=require('../assets/img/Sumi_PoseB_WinterUni_Open.png');
const openBlink=require('../assets/img/Sumi_PoseB_WinterUni_EyesClosed_Open.png');
type AzureScores={recognizedText:string;referenceText:string;pronunciation:number;accuracy:number;fluency:number;completeness:number;clarityLevel:string;recommendation:string;practiceTip:string;sampleResponse:string;englishMeaning?:string;contextEvaluation?:MeaningEvaluation};
type ConversationPhase='opening'|'prompt'|'learner'|'review'|'feedback'|'finished';

export default function GuidedPhraseLiveRoom(){
 const {user}=useContext(AuthContext);const recorderRef=useRef<AudioRecorder|null>(null);const webStreamRef=useRef<any>(null);const webContextRef=useRef<any>(null);const webProcessorRef=useRef<any>(null);const webGainRef=useRef<any>(null);const webRecorderRef=useRef<any>(null);const webChunksRef=useRef<Blob[]>([]);const liveRef=useRef<GeminiGuidedPhraseLive|null>(null);const blinkTimer=useRef<ReturnType<typeof setInterval>|null>(null);const startedAt=useRef(Date.now());const finishingRef=useRef(false);const micBusyRef=useRef(false);const phaseRef=useRef<ConversationPhase>('opening');const nextTurnPendingRef=useRef(false);const preparedTurnRef=useRef<GuidedPhraseTurn|null>(null);const retryTurnRef=useRef<GuidedPhraseTurn|null>(null);const sumiSpokeRef=useRef(false);const azureRef=useRef<AzureScores[]>([]);const evaluationsRef=useRef<MeaningEvaluation[]>([]);const turnsRef=useRef(0);const completedBaseRef=useRef(0);const sessionIdRef=useRef('');const expressionsRef=useRef<string[]>([]);
 const [state,setState]=useState<'connecting'|'ready'|'listening'|'thinking'|'speaking'|'finished'|'error'>('connecting');const [message,setMessage]=useState('Connecting Sumi…');const [turn,setTurn]=useState<GuidedPhraseTurn|null>(null);const [turns,setTurns]=useState(0);const [practicesRemaining,setPracticesRemaining]=useState(5);const [audioUnlocked,setAudioUnlocked]=useState(Platform.OS!=='web');const [blinked,setBlinked]=useState(false);const [mouth,setMouth]=useState(false);const [azure,setAzure]=useState<AzureScores[]>([]);const [evaluations,setEvaluations]=useState<MeaningEvaluation[]>([]);const [heard,setHeard]=useState('');const [accessBlocked,setAccessBlocked]=useState('');const [assessment,setAssessment]=useState<AzureScores|null>(null);const [assessmentError,setAssessmentError]=useState('');const [saveError,setSaveError]=useState('');
 const frame=state==='speaking'?(blinked?openBlink:mouth?open:idle):(blinked?blink:idle);
 const personalize=(text:string)=>text.replace(/\{LEARNER_NAME\}/g,String(user?.fname||'your name').trim()||'your name');
 const publishPreparedTurn=()=>{const value=preparedTurnRef.current;if(!value)return;preparedTurnRef.current=null;sumiSpokeRef.current=false;phaseRef.current='learner';setTurn(value);setState('ready');setMessage('Your turn—tap the microphone and say the phrase.');expressionsRef.current=[...expressionsRef.current,personalize(value.targetJapanese)].slice(-5);setTurns(current=>{const next=Math.min(5,current+1);turnsRef.current=next;return next;});};

 useEffect(()=>{blinkTimer.current=setInterval(()=>{setBlinked(true);setTimeout(()=>setBlinked(false),150);},3400);return()=>{if(blinkTimer.current)clearInterval(blinkTimer.current);};},[]);
 useEffect(()=>{if(state!=='speaking'){setMouth(false);return;}const id=setInterval(()=>setMouth(v=>!v),170);return()=>clearInterval(id);},[state]);
 useEffect(()=>{if(!user?.email){setState('error');setMessage('Sign in to start Guided Phrase Practice.');return;}let active=true;if(Platform.OS!=='web'){AudioManager.setAudioSessionOptions({iosCategory:'playback',iosMode:'spokenAudio',iosOptions:['allowAirPlay','allowBluetoothA2DP']});void AudioManager.setAudioSessionActivity(true).catch(()=>undefined);}
  const start=async()=>{try{const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/live-token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,scenario:'Everyday life in Japan'})});const body=await response.json();if(!response.ok){if(body.accessDisabled){setAccessBlocked(body.message);setState('error');return;}throw new Error(body.message||'Guided Phrase Practice could not start.');}if(!active)return;const resumed=Math.max(0,Math.min(4,Number(body.responsesCompleted||0)));completedBaseRef.current=resumed;turnsRef.current=resumed;setTurns(resumed);sessionIdRef.current=String(body.sessionId||'');setPracticesRemaining(Number(body.practicesRemaining??4));phaseRef.current='opening';const live=new GeminiGuidedPhraseLive({onConnected:()=>{setState('ready');setMessage(resumed?`Welcome back. ${5-resumed} guided responses remain.`:'Sumi is ready. Tap the sound button to begin.');},onSpeaking:value=>{const phase=phaseRef.current;if(value){sumiSpokeRef.current=true;if(phase!=='learner'&&phase!=='review'&&phase!=='finished'){setState('speaking');setMessage(phase==='feedback'?'Listen to Sumi’s feedback…':'Listen to Sumi…');}return;}if((phase==='opening'||phase==='prompt')&&preparedTurnRef.current&&sumiSpokeRef.current){publishPreparedTurn();return;}if(phase==='feedback'){if(nextTurnPendingRef.current&&turnsRef.current<5){nextTurnPendingRef.current=false;phaseRef.current='prompt';setTurn(null);setState('thinking');setMessage('Sumi is preparing your next phrase…');live.requestPracticeTurn();}else{setState('ready');setMessage('Sumi’s feedback is complete.');}return;}if(phase==='learner'){setState(current=>current==='listening'?current:'ready');setMessage('Your turn—tap the microphone and say the phrase.');}},onInputTranscript:text=>setHeard(text),onOutputTranscript:()=>undefined,onTurn:value=>{preparedTurnRef.current=value;},onEvaluation:value=>{evaluationsRef.current=[...evaluationsRef.current,value];setEvaluations(evaluationsRef.current);},onError:text=>{setState('error');setMessage(text);},onComplete:()=>{if(completedBaseRef.current+azureRef.current.length<5){setState('error');setMessage('The conversation ended early. Please return and continue your remaining responses.');}}});liveRef.current=live;await live.connect(body as GuidedLiveAccess);
  }catch(error){setState('error');setMessage(error instanceof Error?error.message:'Guided Phrase Practice could not start.');}};void start();return()=>{active=false;liveRef.current?.close();void recorderRef.current?.stop();webProcessorRef.current?.disconnect?.();webGainRef.current?.disconnect?.();webStreamRef.current?.getTracks?.().forEach((track:any)=>track.stop());void webContextRef.current?.close?.();if(Platform.OS!=='web')void AudioManager.setAudioSessionActivity(false).catch(()=>undefined);};},[user?.email]);
 const startWebMic=async()=>{const mediaDevices=(globalThis.navigator as any)?.mediaDevices;if(!mediaDevices?.getUserMedia)throw new Error('This browser does not support microphone recording.');const stream=await mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const BrowserAudioContext=(globalThis as any).AudioContext||(globalThis as any).webkitAudioContext;const context=new BrowserAudioContext();await context.resume();const source=context.createMediaStreamSource(stream);const processor=context.createScriptProcessor(2048,1,1);const silent=context.createGain();silent.gain.value=0;processor.onaudioprocess=(event:any)=>{const input=event.inputBuffer.getChannelData(0);const ratio=context.sampleRate/16000;const size=Math.max(1,Math.floor(input.length/ratio));const downsampled=new Float32Array(size);for(let i=0;i<size;i++)downsampled[i]=input[Math.min(input.length-1,Math.floor(i*ratio))];liveRef.current?.sendPcm16(downsampled);};source.connect(processor);processor.connect(silent);silent.connect(context.destination);const BrowserMediaRecorder=(globalThis as any).MediaRecorder;if(!BrowserMediaRecorder)throw new Error('This browser cannot prepare pronunciation recordings.');const recorder=new BrowserMediaRecorder(stream);webChunksRef.current=[];recorder.ondataavailable=(event:any)=>{if(event.data?.size)webChunksRef.current.push(event.data);};liveRef.current?.beginUserAudio();recorder.start(250);webStreamRef.current=stream;webContextRef.current=context;webProcessorRef.current=processor;webGainRef.current=silent;webRecorderRef.current=recorder;};
 const stopWebMic=async(completedTurn:GuidedPhraseTurn|null)=>{const recorder=webRecorderRef.current;webRecorderRef.current=null;if(!recorder||!completedTurn){setState('ready');setMessage('Your turn—tap the microphone and try again.');return;}retryTurnRef.current=completedTurn;const blobReady=new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(new Error('The browser could not finish the recording.'));recorder.onstop=()=>resolve(new Blob(webChunksRef.current,{type:recorder.mimeType||'audio/webm'}));});recorder.stop();webProcessorRef.current?.disconnect?.();webProcessorRef.current=null;webGainRef.current?.disconnect?.();webGainRef.current=null;webStreamRef.current?.getTracks?.().forEach((track:any)=>track.stop());webStreamRef.current=null;await webContextRef.current?.close?.();webContextRef.current=null;await liveRef.current?.activateAudio();liveRef.current?.holdPlayback();liveRef.current?.endUserAudio();setState('thinking');setMessage('Reviewing your pronunciation…');const blob=await blobReady;if(blob.size)void assess(blob,personalize(completedTurn.targetJapanese),personalize(completedTurn.englishMeaning));else{setAssessmentError('No speech was recorded. Please try the same phrase again.');setState('ready');}};
 const toggleMic=async()=>{if(micBusyRef.current)return;micBusyRef.current=true;try{if(state==='listening'){await stopMic();return;}if(phaseRef.current!=='learner'||state!=='ready'||!turn)return;setHeard('');await liveRef.current?.activateAudio();setAudioUnlocked(true);liveRef.current?.interrupt();if(Platform.OS==='web')await startWebMic();else{const permission=await AudioManager.requestRecordingPermissions();if(permission!=='Granted')throw new Error('Microphone permission is required.');AudioManager.setAudioSessionOptions({iosCategory:'playAndRecord',iosMode:'default',iosOptions:['defaultToSpeaker','allowBluetoothHFP']});await AudioManager.setAudioSessionActivity(true);const recorder=new AudioRecorder();recorder.enableFileOutput({format:FileFormat.Wav,preset:FilePreset.Medium});recorder.onAudioReady({sampleRate:16000,bufferLength:1600,channelCount:1},({buffer})=>liveRef.current?.sendPcm16(buffer.getChannelData(0)));recorderRef.current=recorder;liveRef.current?.beginUserAudio();const result=await recorder.start();if(result.status==='error')throw new Error(result.message);}setState('listening');setMessage('We’re listening. Say the phrase, then tap Stop.');}catch(error){webStreamRef.current?.getTracks?.().forEach((track:any)=>track.stop());liveRef.current?.endUserAudio();phaseRef.current='learner';setState('ready');setMessage(error instanceof Error?error.message:'The microphone could not start.');}finally{micBusyRef.current=false;}}
 const stopMic=async()=>{const completedTurn=turn;if(completedTurn)retryTurnRef.current=completedTurn;phaseRef.current='review';if(Platform.OS==='web'){await stopWebMic(completedTurn);if(completedTurn)setTurn(null);return;}const recorder=recorderRef.current;if(!recorder){phaseRef.current='learner';setState('ready');setMessage('Your turn—tap the microphone and try again.');return;}setTurn(null);recorderRef.current=null;recorder.clearOnAudioReady();const result=await recorder.stop();AudioManager.setAudioSessionOptions({iosCategory:'playback',iosMode:'spokenAudio',iosOptions:['allowAirPlay','allowBluetoothA2DP']});await AudioManager.setAudioSessionActivity(true).catch(()=>undefined);await liveRef.current?.activateAudio();liveRef.current?.holdPlayback();liveRef.current?.endUserAudio();setState('thinking');setMessage('Reviewing your pronunciation…');if(result.status==='success'&&result.paths[0]&&completedTurn)void assess(result.paths[0],personalize(completedTurn.targetJapanese),personalize(completedTurn.englishMeaning));else{setAssessmentError('No speech was recorded. Please try the same phrase again.');setState('ready');}}
 const assess=async(audio:string|Blob,reference:string,englishMeaning:string)=>{try{setAssessmentError('');const responseIndex=azureRef.current.length;const form=new FormData();if(typeof audio==='string')form.append('audio',{uri:audio.startsWith('file:')?audio:`file://${audio}`,name:'guided-turn.wav',type:'audio/wav'} as any);else form.append('audio',audio,'guided-turn.webm');const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/assess?referenceText=${encodeURIComponent(reference)}`,{method:'POST',body:form});const body=await response.json();if(!response.ok)throw new Error(body.message||'Pronunciation feedback could not be prepared.');for(let attempt=0;attempt<30&&!evaluationsRef.current[responseIndex];attempt++)await new Promise(resolve=>setTimeout(resolve,100));const review={...body,englishMeaning,contextEvaluation:evaluationsRef.current[responseIndex]};azureRef.current=[...azureRef.current,review];setAzure(azureRef.current);setAssessment(review);}catch(error){setAssessmentError(error instanceof Error?error.message:'Pronunciation feedback could not be prepared.');}finally{setState(current=>current==='speaking'||current==='finished'?current:'ready');}}
 const finish=async()=>{if(finishingRef.current)return;finishingRef.current=true;phaseRef.current='finished';setSaveError('');const completedResponses=Math.min(5,completedBaseRef.current+azureRef.current.length);const isComplete=completedResponses>=5;setState('finished');setMessage(isComplete?'Five guided responses complete. Saving your feedback…':`Saving your place. ${5-completedResponses} responses will remain.`);liveRef.current?.close();if(user?.email){const speech=azureRef.current;const meaning=evaluationsRef.current;const avg=(key:keyof AzureScores)=>speech.length?Math.round(speech.reduce((sum,item)=>sum+Number(item[key]||0),0)/speech.length):0;const contextual=meaning.length?Math.round(meaning.reduce((sum,item)=>sum+Number(item.contextScore||0),0)/meaning.length):0;const pronunciation=avg('pronunciation'),accuracy=avg('accuracy'),fluency=avg('fluency'),completeness=avg('completeness');const finalScore=Math.round(((pronunciation+accuracy+fluency+completeness)/4+contextual)/2);const weak=[['Pronunciation',pronunciation],['Accuracy',accuracy],['Fluency',fluency],['Completeness',completeness],['Context',contextual]].filter(([,value])=>Number(value)<75).map(([label])=>String(label));const helpful=meaning.map(item=>item.explanation).filter(Boolean).slice(-2).join(' ');try{const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:sessionIdRef.current,email:user.email,name:`${user.fname??''} ${user.lname??''}`.trim(),scenarioTitle:'First conversations in Japan',durationSeconds:Math.max(1,Math.round((Date.now()-startedAt.current)/1000)),conversationTurns:completedResponses,score:finalScore,pronunciationScore:pronunciation,accuracyScore:accuracy,fluencyScore:fluency,completenessScore:completeness,contextualAccuracy:contextual,expressionsPracticed:expressionsRef.current,areasForImprovement:weak,feedbackSummary:helpful||(isComplete?'You completed the guided conversation. Keep practicing with a steady pace and clear sounds.':'Your place is saved. Continue this five-response practice when you return.')})});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||'Your feedback could not be saved.');setMessage(isComplete?'Your five responses are complete and your feedback is ready.':`Your place is saved. ${5-completedResponses} responses remain.`);}catch(error){setSaveError(error instanceof Error?error.message:'Your feedback could not be saved.');setMessage('Your practice save needs another try.');}}}
 const leave=async()=>{if(state!=='finished'&&(azure.length||turns))await finish();router.replace('/QuackTalk');};
 const reportProblem=()=>{const subject=encodeURIComponent('JapLearn Guided Phrase Practice support');const body=encodeURIComponent('Hello JapLearn Support,\n\nI found a problem in Guided Phrase Practice.\n\nDevice/browser:\nWhat happened:\nSteps to reproduce:\n');void Linking.openURL(`mailto:japlearnofficial@gmail.com?subject=${subject}&body=${body}`);};
 useEffect(()=>{if(completedBaseRef.current+azure.length>=5&&evaluations.length>=azure.length&&state==='ready'&&!assessment){const id=setTimeout(()=>void finish(),900);return()=>clearTimeout(id);}},[evaluations.length,azure.length,state,assessment]);
 const micDisabled=state==='speaking'||state==='connecting'||state==='thinking'||state==='finished'||state==='error'||!!assessment||!!assessmentError;
 const turnLabel=state==='finished'?'SESSION COMPLETE':state==='speaking'?'LISTEN TO SUMI':turn?`YOUR TURN · ${turns} OF 5`:'SUMI IS OPENING THE SESSION';
 const micTitle=state==='listening'?'Recording your response':turn&&state==='ready'?'Your turn to speak':state==='speaking'?'Sumi is speaking':state==='thinking'?'Preparing your feedback':state==='connecting'?'Opening the voice room':state==='finished'?'Practice complete':'Get ready to listen';
 const micHint=state==='listening'?'Say the phrase clearly, then tap Stop.':turn&&state==='ready'?'Tap the microphone when you are ready.':message;
 return <SafeAreaView style={styles.safeArea}>
  <ImageBackground source={bg} style={[styles.background,{backgroundColor:'#171934'}]} imageStyle={styles.backgroundArtwork} resizeMode="cover">
   <View style={[styles.sceneTint,styles.studioTint]}/>
   <View style={styles.header}>
    <Pressable onPress={()=>void leave()} style={styles.headerButton}><BackIcon width={18} height={18} fill="#47295A"/></Pressable>
    <View style={[styles.headerMark,{backgroundColor:'#FCE9F1'}]}><Ionicons name="mic" size={18} color="#D84F83"/></View>
    <View style={styles.headerCopy}><Text style={[styles.headerEyebrow,{color:'#D84F83'}]}>VOICE STUDIO · {turns}/5</Text><Text style={styles.headerTitle}>Guided Phrase</Text></View>
    <Pressable accessibilityLabel="Open guided feedback" onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})} style={[styles.headerButton,{backgroundColor:'#FCE9F1'}]}><Ionicons name="analytics-outline" size={21} color="#D84F83"/></Pressable>
   </View>
   <View style={styles.stage}>
    <View style={styles.coachStatus}><View style={styles.onlineDot}/><View><Text style={styles.coachStatusText}>SUMI'S VOICE ROOM</Text><Text style={styles.coachStatusSubtext}>{state.toUpperCase()}</Text></View></View>
    <Image source={frame} style={styles.sumi} resizeMode="contain"/>
    <View style={[styles.controlPanel,{paddingBottom:16}]}>
     {!audioUnlocked&&state!=='connecting'&&state!=='error'&&<Pressable onPress={()=>void liveRef.current?.activateAudio().then(()=>setAudioUnlocked(true)).catch(()=>setMessage('Tap again to enable Sumi’s voice.'))} style={[styles.tutorialDone,{backgroundColor:'#7552C8',marginTop:0,marginBottom:12,flexDirection:'row',gap:8}]}><Ionicons name="volume-high" size={19} color="#FFFFFF"/><Text style={styles.tutorialDoneText}>Tap to hear Sumi</Text></Pressable>}
     {state!=='finished'?<><View style={styles.guidedPromptCard}><View style={styles.guidedPromptTop}><View style={[styles.promptIcon,{backgroundColor:'#FCE9F1'}]}><Ionicons name={state==='speaking'?'volume-high':'chatbubble-ellipses'} size={20} color="#D84F83"/></View><View style={styles.promptCopy}><Text style={[styles.promptLabel,{color:'#D84F83'}]}>{turnLabel}</Text>{turn?.learnerInstruction&&state!=='speaking'?<Text style={styles.guidedInstruction}>{personalize(turn.learnerInstruction)}</Text>:null}</View></View>{!turn?<Text style={styles.promptTitle}>{message}</Text>:state!=='speaking'?<View style={styles.phraseTranscript}><Text style={styles.phraseJapanese}>{personalize(turn.targetJapanese)}</Text>{turn.targetRomaji?<Text style={styles.phraseRomaji}>{personalize(turn.targetRomaji)}</Text>:null}{turn.englishMeaning?<Text style={styles.phraseMeaning}>{personalize(turn.englishMeaning)}</Text>:null}</View>:<Text style={styles.promptTitle}>Listen first. Your phrase will appear when Sumi finishes.</Text>}</View>
     <View style={[styles.learnerMicCard,state==='listening'&&styles.learnerMicCardActive]}><View style={styles.learnerMicCopy}><Text style={styles.learnerMicEyebrow}>{state==='listening'?'RECORDING':'VOICE RESPONSE'}</Text><Text style={styles.learnerMicTitle}>{micTitle}</Text><Text style={styles.microphoneStatus}>{micHint}</Text></View><Pressable disabled={micDisabled} accessibilityRole="button" accessibilityLabel={state==='listening'?'Stop recording':'Start recording'} onPress={()=>void toggleMic()} style={({pressed})=>[styles.microphoneButton,{backgroundColor:state==='listening'?'#E34F6C':'#D84F83',opacity:micDisabled?0.48:1},pressed&&!micDisabled&&styles.microphonePressed]}><Ionicons name={state==='listening'?'stop':'mic'} size={26} color="#fff"/></Pressable></View></>:<View style={styles.sessionCompleteCard}><View style={styles.sessionCompleteIcon}><Ionicons name="checkmark" size={28} color="#FFFFFF"/></View><Text style={styles.sessionCompleteEyebrow}>GUIDED PRACTICE COMPLETE</Text><Text style={styles.sessionCompleteTitle}>You finished all five phrases.</Text><Text style={styles.sessionCompleteText}>{message}</Text><View style={styles.sessionCompleteActions}><Pressable style={styles.sessionCompleteSecondary} onPress={()=>router.replace('/QuackTalk')}><Ionicons name="arrow-back" size={17} color="#7552C8"/><Text style={styles.sessionCompleteSecondaryText}>Back to QuackTalk</Text></Pressable><Pressable style={styles.sessionCompletePrimary} onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})}><Ionicons name="analytics-outline" size={17} color="#FFFFFF"/><Text style={styles.sessionCompletePrimaryText}>View feedback</Text></Pressable></View></View>}
     {state!=='finished'?<View style={{flexDirection:'row',gap:9,marginTop:12}}>
      <Pressable onPress={reportProblem} style={[styles.headerButton,{flex:1,width:'auto',height:44,flexDirection:'row',gap:7}]}><Ionicons name="flag-outline" size={17} color="#7552C8"/><Text style={{fontFamily:'Jua',fontSize:11,color:'#7552C8'}}>Report a problem</Text></Pressable>
      <Pressable onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})} style={[styles.headerButton,{flex:1,width:'auto',height:44,flexDirection:'row',gap:7,backgroundColor:'#FCE9F1'}]}><Ionicons name="analytics-outline" size={17} color="#D84F83"/><Text style={{fontFamily:'Jua',fontSize:11,color:'#D84F83'}}>Feedback</Text></Pressable>
     </View>:null}
     {!!saveError&&<><Text style={[styles.assessmentMeaning,{textAlign:'center',marginTop:10}]}>{saveError}</Text><Pressable onPress={()=>{finishingRef.current=false;void finish();}} style={[styles.tutorialDone,{backgroundColor:'#D84F83'}]}><Text style={styles.tutorialDoneText}>Retry saving feedback</Text></Pressable></>}
    </View>
   </View>
   <Modal visible={!!accessBlocked} transparent animationType="fade" onRequestClose={()=>router.replace('/QuackTalk')}>
    <View style={styles.assessmentBackdrop}><View style={styles.assessmentCard}><View style={styles.assessmentContent}><View style={styles.assessmentHeader}><View style={[styles.assessmentIcon,{backgroundColor:'#D84F83'}]}><Ionicons name="lock-closed" size={22} color="#FFFFFF"/></View><View style={{flex:1}}><Text style={styles.assessmentEyebrow}>GUIDED PHRASE PRACTICE</Text><Text style={styles.assessmentTitle}>Practice access is paused</Text></View></View><View style={styles.assessmentSection}><Text style={styles.assessmentBody}>{accessBlocked}</Text></View><Pressable style={styles.assessmentContinue} onPress={()=>router.replace('/QuackTalk')}><Text style={styles.assessmentContinueText}>Okay</Text></Pressable></View></View></View>
   </Modal>
   <Modal visible={!!assessment||!!assessmentError} transparent animationType="fade" onRequestClose={()=>{setAssessment(null);setAssessmentError('');}}>
    <View style={styles.assessmentBackdrop}>
     <View style={styles.assessmentCard}>
      <View style={styles.assessmentContent}>
       <View style={styles.assessmentHeader}><View style={styles.assessmentIcon}><Ionicons name="pulse" size={24} color="#FFFFFF"/></View><View style={{flex:1}}><Text style={styles.assessmentEyebrow}>PRONUNCIATION REVIEW</Text><Text style={styles.assessmentTitle}>{assessment?.clarityLevel||'Review unavailable'}</Text></View></View>
       {assessment?<>
        <View style={styles.assessmentScoreRow}>
         <AssessmentMetric label="Pronunciation" value={assessment.pronunciation}/><AssessmentMetric label="Accuracy" value={assessment.accuracy}/><AssessmentMetric label="Fluency" value={assessment.fluency}/><AssessmentMetric label="Complete" value={assessment.completeness}/>
        </View>
        <View style={styles.assessmentAdvice}><Ionicons name="heart" size={18} color="#7552C8"/><View style={{flex:1}}><Text style={styles.assessmentLabel}>SUMI'S NOTE</Text><Text style={styles.assessmentBody}>{sumiAssessmentNote(assessment)}</Text></View></View>
        <View style={styles.assessmentCompareRow}><View style={[styles.assessmentSection,styles.assessmentCompareCell]}><Text style={styles.assessmentLabel}>WE HEARD</Text><Text style={styles.assessmentHeard}>{assessment.recognizedText||'No clear phrase detected'}</Text></View><View style={[styles.assessmentSection,styles.assessmentCompareCell]}><Text style={styles.assessmentLabel}>MODEL PHRASE</Text><Text style={styles.assessmentJapanese}>{assessment.sampleResponse||assessment.referenceText}</Text>{assessment.englishMeaning?<Text style={styles.assessmentMeaning}>{assessment.englishMeaning}</Text>:null}</View></View>
        {assessment.contextEvaluation?<View style={styles.assessmentSection}><Text style={styles.assessmentLabel}>WHY IT FITS THE MOMENT</Text><Text style={styles.assessmentBody}>{assessment.contextEvaluation.explanation}</Text>{assessment.contextEvaluation.betterResponse?<Text style={styles.assessmentMeaning}>A stronger response: {assessment.contextEvaluation.betterResponse}</Text>:null}</View>:null}
        <View style={styles.assessmentTip}><Ionicons name="sparkles" size={18} color="#D84F83"/><View style={{flex:1}}><Text style={[styles.assessmentLabel,{color:'#B23D6B'}]}>YOUR NEXT STEP</Text><Text style={styles.assessmentBody}>{assessment.recommendation} {assessment.practiceTip}</Text></View></View>
       </>:<View style={styles.assessmentSection}><Text style={styles.assessmentBody}>{assessmentError}</Text><Text style={styles.assessmentMeaning}>You can continue the conversation and review the next phrase.</Text></View>}
       <Pressable style={styles.assessmentContinue} onPress={()=>{const mustRetry=!!assessmentError&&!assessment;setAssessment(null);setAssessmentError('');if(mustRetry){nextTurnPendingRef.current=false;liveRef.current?.interrupt();phaseRef.current='learner';setTurn(retryTurnRef.current);setState('ready');setMessage('Your turn—tap the microphone and try the same phrase again.');return;}retryTurnRef.current=null;phaseRef.current='feedback';if(turnsRef.current<5){nextTurnPendingRef.current=true;setTurn(null);setState('thinking');setMessage('Listen to Sumi’s response. Your next phrase will follow.');}liveRef.current?.releasePlayback();}}><Text style={styles.assessmentContinueText}>{assessmentError&&!assessment?'Try this phrase again':'Continue with Sumi'}</Text><Ionicons name={assessmentError&&!assessment?'refresh':'arrow-forward'} size={18} color="#FFFFFF"/></Pressable>
      </View>
     </View>
    </View>
   </Modal>
  </ImageBackground>
 </SafeAreaView>;
}

function AssessmentMetric({label,value}:{label:string;value:number}){return <View style={styles.assessmentMetric}><Text style={styles.assessmentMetricValue}>{Math.round(value||0)}</Text><Text style={styles.assessmentMetricLabel}>{label}</Text></View>}
function sumiAssessmentNote(result:AzureScores){const average=(Number(result.pronunciation||0)+Number(result.accuracy||0)+Number(result.fluency||0)+Number(result.completeness||0))/4;if(average>=85)return 'よくできました！ You communicated the phrase clearly. Keep this relaxed pace for the next situation.';if(average>=70)return 'いいですね！ Your phrase was understandable. One more careful repetition will make the sounds smoother and more confident.';return '惜しいです！ You are building the phrase correctly. Slow down, follow the model in short sound groups, and try again without rushing.';}
