import { Ionicons } from '@expo/vector-icons';
import { AudioManager, AudioRecorder, FileFormat, FilePreset } from 'react-native-audio-api';
import { router } from 'expo-router';
import React, { useContext, useEffect, useRef, useState } from 'react';
import { Image, ImageBackground, Linking, Modal, Platform, Pressable, SafeAreaView, ScrollView, Text, View } from 'react-native';
import BackIcon from '../assets/svg/back-icon.svg';
import { AuthContext } from '../context/AuthContext';
import expoconfig from '../expoconfig';
import styles from '../styles/stylesQuackTalkPracticeRoom';
import { GeminiGuidedPhraseLive, GuidedLiveAccess, GuidedPhraseTurn, MeaningEvaluation } from '../services/guidedPhraseLive';

const bg=require('../assets/quacktalk/guided-phrase-studio-v1.png');
const idle=require('../assets/img/Sumi_PoseB_WinterUni_Smile.png');
const blink=require('../assets/img/Sumi_PoseB_WinterUni_EyesClosed_Smile.png');
const open=require('../assets/img/Sumi_PoseB_WinterUni_Open.png');
const openBlink=require('../assets/img/Sumi_PoseB_WinterUni_EyesClosed_Open.png');
type AzureScores={recognizedText:string;referenceText:string;pronunciation:number;accuracy:number;fluency:number;completeness:number;clarityLevel:string;recommendation:string;practiceTip:string;sampleResponse:string;englishMeaning?:string};

export default function GuidedPhraseLiveRoom(){
 const {user}=useContext(AuthContext);const recorderRef=useRef<AudioRecorder|null>(null);const webStreamRef=useRef<any>(null);const webContextRef=useRef<any>(null);const webProcessorRef=useRef<any>(null);const webRecorderRef=useRef<any>(null);const webChunksRef=useRef<Blob[]>([]);const liveRef=useRef<GeminiGuidedPhraseLive|null>(null);const blinkTimer=useRef<ReturnType<typeof setInterval>|null>(null);const startedAt=useRef(Date.now());const finishingRef=useRef(false);const azureRef=useRef<AzureScores[]>([]);const evaluationsRef=useRef<MeaningEvaluation[]>([]);const turnsRef=useRef(0);const expressionsRef=useRef<string[]>([]);
 const [state,setState]=useState<'connecting'|'ready'|'listening'|'thinking'|'speaking'|'finished'|'error'>('connecting');const [message,setMessage]=useState('Connecting Sumi…');const [turn,setTurn]=useState<GuidedPhraseTurn|null>(null);const [turns,setTurns]=useState(0);const [practicesRemaining,setPracticesRemaining]=useState(5);const [audioUnlocked,setAudioUnlocked]=useState(Platform.OS!=='web');const [blinked,setBlinked]=useState(false);const [mouth,setMouth]=useState(false);const [azure,setAzure]=useState<AzureScores[]>([]);const [evaluations,setEvaluations]=useState<MeaningEvaluation[]>([]);const [sumiText,setSumiText]=useState('');const [heard,setHeard]=useState('');const [accessBlocked,setAccessBlocked]=useState('');const [assessment,setAssessment]=useState<AzureScores|null>(null);const [assessmentError,setAssessmentError]=useState('');
 const frame=state==='speaking'?(blinked?openBlink:mouth?open:idle):(blinked?blink:idle);

 useEffect(()=>{blinkTimer.current=setInterval(()=>{setBlinked(true);setTimeout(()=>setBlinked(false),150);},3400);return()=>{if(blinkTimer.current)clearInterval(blinkTimer.current);};},[]);
 useEffect(()=>{if(state!=='speaking'){setMouth(false);return;}const id=setInterval(()=>setMouth(v=>!v),170);return()=>clearInterval(id);},[state]);
 useEffect(()=>{if(!user?.email){setState('error');setMessage('Sign in to start Guided Phrase Practice.');return;}let active=true;
  const start=async()=>{try{const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/live-token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,scenario:'First conversations in Japan'})});const body=await response.json();if(!response.ok){if(body.accessDisabled){setAccessBlocked(body.message);setState('error');return;}throw new Error(body.message||'Guided Phrase Practice could not start.');}if(!active)return;setPracticesRemaining(Number(body.practicesRemaining??4));const live=new GeminiGuidedPhraseLive({onConnected:()=>{setState('ready');setMessage('Sumi is ready.');},onSpeaking:value=>{if(value){setState('speaking');setMessage('Sumi is speaking…');}else setState(current=>current==='listening'||current==='finished'?current:'ready');},onInputTranscript:text=>setHeard(text),onOutputTranscript:text=>setSumiText(previous=>previous+text),onTurn:value=>{setTurn(value);expressionsRef.current=[...expressionsRef.current,value.targetJapanese].slice(-5);setTurns(current=>{const next=Math.min(5,current+1);turnsRef.current=next;return next;});setSumiText('');},onEvaluation:value=>{evaluationsRef.current=[...evaluationsRef.current,value];setEvaluations(evaluationsRef.current);},onError:text=>{setState('error');setMessage(text);},onComplete:()=>{if(turnsRef.current>=5)setTimeout(()=>void finish(),4000);else{setState('error');setMessage('The conversation ended early. Please return and try again.');}}});liveRef.current=live;await live.connect(body as GuidedLiveAccess);
  }catch(error){setState('error');setMessage(error instanceof Error?error.message:'Guided Phrase Practice could not start.');}};void start();return()=>{active=false;liveRef.current?.close();void recorderRef.current?.stop();webProcessorRef.current?.disconnect?.();webStreamRef.current?.getTracks?.().forEach((track:any)=>track.stop());void webContextRef.current?.close?.();};},[user?.email]);
 const startWebMic=async()=>{const mediaDevices=(globalThis.navigator as any)?.mediaDevices;if(!mediaDevices?.getUserMedia)throw new Error('This browser does not support microphone recording.');const stream=await mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const BrowserAudioContext=(globalThis as any).AudioContext||(globalThis as any).webkitAudioContext;const context=new BrowserAudioContext();await context.resume();const source=context.createMediaStreamSource(stream);const processor=context.createScriptProcessor(2048,1,1);processor.onaudioprocess=(event:any)=>{const input=event.inputBuffer.getChannelData(0);const ratio=context.sampleRate/16000;const size=Math.max(1,Math.floor(input.length/ratio));const downsampled=new Float32Array(size);for(let i=0;i<size;i++)downsampled[i]=input[Math.min(input.length-1,Math.floor(i*ratio))];liveRef.current?.sendPcm16(downsampled);};source.connect(processor);processor.connect(context.destination);const BrowserMediaRecorder=(globalThis as any).MediaRecorder;if(!BrowserMediaRecorder)throw new Error('This browser cannot prepare pronunciation recordings.');const recorder=new BrowserMediaRecorder(stream);webChunksRef.current=[];recorder.ondataavailable=(event:any)=>{if(event.data?.size)webChunksRef.current.push(event.data);};recorder.start(250);webStreamRef.current=stream;webContextRef.current=context;webProcessorRef.current=processor;webRecorderRef.current=recorder;};
 const stopWebMic=async(completedTurn:GuidedPhraseTurn|null)=>{const recorder=webRecorderRef.current;webRecorderRef.current=null;liveRef.current?.endUserAudio();webProcessorRef.current?.disconnect?.();webProcessorRef.current=null;webStreamRef.current?.getTracks?.().forEach((track:any)=>track.stop());webStreamRef.current=null;await webContextRef.current?.close?.();webContextRef.current=null;setState('thinking');setMessage('Sumi is reviewing your answer…');if(!recorder||!completedTurn)return;const blob=await new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(new Error('The browser could not finish the recording.'));recorder.onstop=()=>resolve(new Blob(webChunksRef.current,{type:recorder.mimeType||'audio/webm'}));recorder.stop();});if(blob.size)void assess(blob,completedTurn.targetJapanese,completedTurn.englishMeaning);else{setAssessmentError('No speech was recorded. Please try the phrase again.');setState('ready');}};
 const toggleMic=async()=>{if(state==='listening'){await stopMic();return;}if(state==='connecting'||state==='speaking'||state==='thinking'||state==='finished')return;if(!turn){setState('thinking');setMessage('Sumi is preparing your next phrase…');liveRef.current?.requestPracticeTurn();return;}try{setHeard('');liveRef.current?.interrupt();if(Platform.OS==='web')await startWebMic();else{const permission=await AudioManager.requestRecordingPermissions();if(permission!=='Granted')throw new Error('Microphone permission is required.');await AudioManager.setAudioSessionActivity(true);const recorder=new AudioRecorder();recorder.enableFileOutput({format:FileFormat.Wav,preset:FilePreset.Medium});recorder.onAudioReady({sampleRate:16000,bufferLength:1600,channelCount:1},({buffer})=>liveRef.current?.sendPcm16(buffer.getChannelData(0)));recorderRef.current=recorder;const result=await recorder.start();if(result.status==='error')throw new Error(result.message);}setState('listening');setMessage('Listening—speak your answer, then tap again.');}catch(error){webStreamRef.current?.getTracks?.().forEach((track:any)=>track.stop());setState('error');setMessage(error instanceof Error?error.message:'The microphone could not start.');}}
 const stopMic=async()=>{const completedTurn=turn;setTurn(null);if(Platform.OS==='web'){await stopWebMic(completedTurn);return;}const recorder=recorderRef.current;if(!recorder)return;recorderRef.current=null;recorder.clearOnAudioReady();const result=await recorder.stop();liveRef.current?.endUserAudio();await AudioManager.setAudioSessionActivity(false);setState('thinking');setMessage('Sumi is reviewing your answer…');if(result.status==='success'&&result.paths[0]&&completedTurn)void assess(result.paths[0],completedTurn.targetJapanese,completedTurn.englishMeaning);}
 const assess=async(audio:string|Blob,reference:string,englishMeaning:string)=>{try{setAssessmentError('');const form=new FormData();if(typeof audio==='string')form.append('audio',{uri:audio.startsWith('file:')?audio:`file://${audio}`,name:'guided-turn.wav',type:'audio/wav'} as any);else form.append('audio',audio,'guided-turn.webm');const response=await fetch(`${expoconfig.API_URL}/api/guided-phrase/assess?referenceText=${encodeURIComponent(reference)}`,{method:'POST',body:form});const body=await response.json();if(!response.ok)throw new Error(body.message||'Pronunciation feedback could not be prepared.');const review={...body,englishMeaning};azureRef.current=[...azureRef.current,review];setAzure(azureRef.current);setAssessment(review);}catch(error){setAssessmentError(error instanceof Error?error.message:'Pronunciation feedback could not be prepared.');}finally{setState(current=>current==='speaking'||current==='finished'?current:'ready');}}
 const finish=async()=>{if(finishingRef.current)return;finishingRef.current=true;setState('finished');setMessage('Five guided responses complete. Your feedback is ready.');liveRef.current?.close();if(user?.email){const speech=azureRef.current;const meaning=evaluationsRef.current;const avg=(key:keyof AzureScores)=>speech.length?Math.round(speech.reduce((sum,item)=>sum+Number(item[key]||0),0)/speech.length):0;const contextual=meaning.length?Math.round(meaning.reduce((sum,item)=>sum+Number(item.contextScore||0),0)/meaning.length):0;const pronunciation=avg('pronunciation'),accuracy=avg('accuracy'),fluency=avg('fluency'),completeness=avg('completeness');const finalScore=Math.round(((pronunciation+accuracy+fluency+completeness)/4+contextual)/2);const weak=[['Pronunciation',pronunciation],['Accuracy',accuracy],['Fluency',fluency],['Completeness',completeness],['Context',contextual]].filter(([,value])=>Number(value)<75).map(([label])=>String(label));const helpful=meaning.map(item=>item.explanation).filter(Boolean).slice(-2).join(' ');await fetch(`${expoconfig.API_URL}/api/guided-phrase/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,name:`${user.fname??''} ${user.lname??''}`.trim(),scenarioTitle:'First conversations in Japan',durationSeconds:Math.max(1,Math.round((Date.now()-startedAt.current)/1000)),conversationTurns:turnsRef.current,score:finalScore,pronunciationScore:pronunciation,accuracyScore:accuracy,fluencyScore:fluency,completenessScore:completeness,contextualAccuracy:contextual,expressionsPracticed:expressionsRef.current,areasForImprovement:weak,feedbackSummary:helpful||'You completed the guided conversation. Keep practicing with a steady pace and clear sounds.'})}).catch(()=>undefined);}}
 const leave=async()=>{if(state!=='finished'&&(azure.length||turns))await finish();router.replace('/QuackTalk');};
 const reportProblem=()=>{const subject=encodeURIComponent('JapLearn Guided Phrase Practice support');const body=encodeURIComponent('Hello JapLearn Support,\n\nI found a problem in Guided Phrase Practice.\n\nDevice/browser:\nWhat happened:\nSteps to reproduce:\n');void Linking.openURL(`mailto:japlearnofficial@gmail.com?subject=${subject}&body=${body}`);};
 useEffect(()=>{if(evaluations.length>=5&&state!=='finished'){const id=setTimeout(()=>void finish(),azure.length>=5?1800:6000);return()=>clearTimeout(id);}},[evaluations.length,azure.length,state]);
 return <SafeAreaView style={styles.safeArea}>
  <ImageBackground source={bg} style={[styles.background,{backgroundColor:'#171934'}]} imageStyle={styles.backgroundArtwork} resizeMode="cover">
   <View style={[styles.sceneTint,styles.studioTint]}/>
   <View style={styles.header}>
    <Pressable onPress={()=>void leave()} style={styles.headerButton}><BackIcon width={18} height={18} fill="#47295A"/></Pressable>
    <View style={[styles.headerMark,{backgroundColor:'#FCE9F1'}]}><Ionicons name="mic" size={18} color="#D84F83"/></View>
    <View style={styles.headerCopy}><Text style={[styles.headerEyebrow,{color:'#D84F83'}]}>VOICE STUDIO · {turns}/5</Text><Text style={styles.headerTitle}>Guided Phrase</Text></View>
    <Pressable accessibilityLabel="Open guided feedback" onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})} style={[styles.headerButton,{backgroundColor:'#FCE9F1'}]}><Ionicons name="analytics-outline" size={21} color="#D84F83"/></Pressable>
   </View>
   <View style={styles.stage}>
    <View style={styles.coachStatus}><View style={styles.onlineDot}/><View><Text style={styles.coachStatusText}>SUMI'S VOICE ROOM</Text><Text style={styles.coachStatusSubtext}>{state.toUpperCase()}</Text></View></View>
    <Image source={frame} style={styles.sumi} resizeMode="contain"/>
    <View style={[styles.controlPanel,{paddingBottom:16}]}>
     {!audioUnlocked&&state!=='connecting'&&state!=='error'&&<Pressable onPress={()=>void liveRef.current?.activateAudio().then(()=>setAudioUnlocked(true)).catch(()=>setMessage('Tap again to enable Sumi’s voice.'))} style={[styles.tutorialDone,{backgroundColor:'#7552C8',marginTop:0,marginBottom:12,flexDirection:'row',gap:8}]}><Ionicons name="volume-high" size={19} color="#FFFFFF"/><Text style={styles.tutorialDoneText}>Tap to hear Sumi</Text></Pressable>}
     <View style={styles.promptRow}><View style={[styles.promptIcon,{backgroundColor:'#FCE9F1'}]}><Ionicons name="chatbubble-ellipses" size={20} color="#D84F83"/></View><View style={styles.promptCopy}><Text style={[styles.promptLabel,{color:'#D84F83'}]}>{state==='finished'?'SESSION COMPLETE':turn?`PRACTICE ${turns} OF 5`:'SUMI IS OPENING THE SESSION'}</Text><Text style={styles.promptTitle}>{turn?.learnerInstruction||sumiText||message}</Text>{turn?.targetJapanese?<Text style={styles.assessmentJapanese}>{turn.targetJapanese}</Text>:null}{turn?.targetRomaji?<Text style={styles.assessmentMeaning}>{turn.targetRomaji}</Text>:null}{turn&&<Text style={styles.promptNote}>{turn.englishMeaning}</Text>}{heard?<Text style={styles.promptNote}>Heard: {heard}</Text>:null}</View></View>
     <View style={styles.microphoneArea}><Pressable disabled={state==='speaking'||state==='connecting'||state==='thinking'||state==='finished'} onPress={()=>void toggleMic()} style={({pressed})=>[styles.microphoneButton,{backgroundColor:state==='listening'?'#E34F6C':'#D84F83',opacity:state==='speaking'||state==='connecting'||state==='thinking'||state==='finished'?0.55:1},pressed&&styles.microphonePressed]}><Ionicons name={state==='listening'?'stop':'mic'} size={26} color="#fff"/></Pressable><Text style={styles.microphoneStatus}>{message}</Text></View>
     <View style={{flexDirection:'row',gap:9,marginTop:12}}>
      <Pressable onPress={reportProblem} style={[styles.headerButton,{flex:1,width:'auto',height:44,flexDirection:'row',gap:7}]}><Ionicons name="flag-outline" size={17} color="#7552C8"/><Text style={{fontFamily:'Jua',fontSize:11,color:'#7552C8'}}>Report a problem</Text></Pressable>
      <Pressable onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})} style={[styles.headerButton,{flex:1,width:'auto',height:44,flexDirection:'row',gap:7,backgroundColor:'#FCE9F1'}]}><Ionicons name="analytics-outline" size={17} color="#D84F83"/><Text style={{fontFamily:'Jua',fontSize:11,color:'#D84F83'}}>Feedback</Text></Pressable>
     </View>
     {state==='finished'&&<Pressable onPress={()=>router.push({pathname:'/QuackTalkFeedback',params:{returnTo:'speaking'}})} style={[styles.tutorialDone,{backgroundColor:'#D84F83'}]}><Text style={styles.tutorialDoneText}>View guided feedback</Text></Pressable>}
    </View>
   </View>
   <Modal visible={!!accessBlocked} transparent animationType="fade" onRequestClose={()=>router.replace('/QuackTalk')}>
    <View style={styles.assessmentBackdrop}><View style={styles.assessmentCard}><View style={styles.assessmentContent}><View style={styles.assessmentHeader}><View style={[styles.assessmentIcon,{backgroundColor:'#D84F83'}]}><Ionicons name="lock-closed" size={22} color="#FFFFFF"/></View><View style={{flex:1}}><Text style={styles.assessmentEyebrow}>GUIDED PHRASE PRACTICE</Text><Text style={styles.assessmentTitle}>Practice access is paused</Text></View></View><View style={styles.assessmentSection}><Text style={styles.assessmentBody}>{accessBlocked}</Text></View><Pressable style={styles.assessmentContinue} onPress={()=>router.replace('/QuackTalk')}><Text style={styles.assessmentContinueText}>Okay</Text></Pressable></View></View></View>
   </Modal>
   <Modal visible={!!assessment||!!assessmentError} transparent animationType="fade" onRequestClose={()=>{setAssessment(null);setAssessmentError('');}}>
    <View style={styles.assessmentBackdrop}>
     <View style={styles.assessmentCard}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.assessmentContent}>
       <View style={styles.assessmentHeader}><View style={styles.assessmentIcon}><Ionicons name="waveform" size={24} color="#FFFFFF"/></View><View style={{flex:1}}><Text style={styles.assessmentEyebrow}>PRONUNCIATION REVIEW</Text><Text style={styles.assessmentTitle}>{assessment?.clarityLevel||'Review unavailable'}</Text></View></View>
       {assessment?<>
        <View style={styles.assessmentScoreRow}>
         <AssessmentMetric label="Pronunciation" value={assessment.pronunciation}/><AssessmentMetric label="Accuracy" value={assessment.accuracy}/><AssessmentMetric label="Fluency" value={assessment.fluency}/><AssessmentMetric label="Complete" value={assessment.completeness}/>
        </View>
        <View style={styles.assessmentSection}><Text style={styles.assessmentLabel}>WHAT WAS HEARD</Text><Text style={styles.assessmentHeard}>{assessment.recognizedText||'No clear phrase was detected.'}</Text></View>
        <View style={styles.assessmentSection}><Text style={styles.assessmentLabel}>MODEL PHRASE</Text><Text style={styles.assessmentJapanese}>{assessment.sampleResponse||assessment.referenceText}</Text>{assessment.englishMeaning?<Text style={styles.assessmentMeaning}>{assessment.englishMeaning}</Text>:null}</View>
        <View style={styles.assessmentAdvice}><Ionicons name="sparkles" size={18} color="#7552C8"/><View style={{flex:1}}><Text style={styles.assessmentLabel}>RECOMMENDATION</Text><Text style={styles.assessmentBody}>{assessment.recommendation}</Text></View></View>
        <View style={styles.assessmentTip}><Ionicons name="ear-outline" size={18} color="#D84F83"/><View style={{flex:1}}><Text style={[styles.assessmentLabel,{color:'#B23D6B'}]}>TRY THIS NEXT</Text><Text style={styles.assessmentBody}>{assessment.practiceTip}</Text></View></View>
       </>:<View style={styles.assessmentSection}><Text style={styles.assessmentBody}>{assessmentError}</Text><Text style={styles.assessmentMeaning}>You can continue the conversation and review the next phrase.</Text></View>}
       <Pressable style={styles.assessmentContinue} onPress={()=>{setAssessment(null);setAssessmentError('');}}><Text style={styles.assessmentContinueText}>Continue with Sumi</Text><Ionicons name="arrow-forward" size={18} color="#FFFFFF"/></Pressable>
      </ScrollView>
     </View>
    </View>
   </Modal>
  </ImageBackground>
 </SafeAreaView>;
}

function AssessmentMetric({label,value}:{label:string;value:number}){return <View style={styles.assessmentMetric}><Text style={styles.assessmentMetricValue}>{Math.round(value||0)}</Text><Text style={styles.assessmentMetricLabel}>{label}</Text></View>}
