import { Ionicons } from '@expo/vector-icons';
import React,{useEffect,useState} from 'react';
import { Image,ImageBackground,StyleSheet,Text,View } from 'react-native';

type Props={title:string;subtitle:string;status:string;color:string;icon:keyof typeof Ionicons.glyphMap;onComplete:()=>void};
export default function QuackSituateExit({title,subtitle,status,color,icon,onComplete}:Props){
 const [progress,setProgress]=useState(8);
 useEffect(()=>{const tick=setInterval(()=>setProgress(v=>Math.min(100,v+8)),80);const done=setTimeout(onComplete,1150);return()=>{clearInterval(tick);clearTimeout(done);};},[onComplete]);
 return <ImageBackground source={require('../assets/quacksituate/quacksituate-loading-v2.png')} style={s.screen} resizeMode="cover"><View style={s.shade}/><View style={s.content}><View style={s.badge}><Ionicons name={icon} size={15} color={color}/><Text style={[s.badgeText,{color}]}>JAPLEARN SITUATION QUEST</Text></View><View style={s.portal}><View style={[s.halo,{borderColor:`${color}88`,backgroundColor:`${color}22`}]}/><Image source={require('../assets/hello.png')} style={s.mascot}/></View><Text style={s.bye}>またね · MATA NE</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text><View style={s.track}><View style={[s.fill,{width:`${progress}%`,backgroundColor:color}]}/></View><Text style={s.status}>{progress<100?`${status} · ${progress}%`:'SEE YOU NEXT MISSION!'}</Text></View></ImageBackground>;
}
const s=StyleSheet.create({screen:{flex:1,alignItems:'center',justifyContent:'center'},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(43,23,52,.5)'},content:{width:'88%',maxWidth:430,alignItems:'center'},badge:{flexDirection:'row',alignItems:'center',gap:7,backgroundColor:'#FFF',borderRadius:999,paddingHorizontal:14,paddingVertical:10},badgeText:{fontSize:8,fontWeight:'900',letterSpacing:1.2},portal:{width:220,height:220,alignItems:'center',justifyContent:'center',marginTop:22},halo:{position:'absolute',width:190,height:190,borderRadius:95,borderWidth:2},mascot:{width:180,height:190,resizeMode:'contain'},bye:{fontSize:10,fontWeight:'900',letterSpacing:1.6,color:'#C8F2A8'},title:{fontFamily:'Jua',fontSize:38,color:'#FFF',textAlign:'center',marginTop:8},subtitle:{fontSize:13,lineHeight:20,color:'#F4EDF6',textAlign:'center',marginTop:7},track:{width:'100%',height:12,borderRadius:8,backgroundColor:'rgba(255,255,255,.75)',overflow:'hidden',marginTop:25},fill:{height:'100%',borderRadius:8},status:{fontSize:10,fontWeight:'900',letterSpacing:1.1,color:'#FFF',marginTop:12}});
