import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8F3FB' },
  background: { flex: 1 },
  overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(249,245,251,0.86)' },
  header: {
    margin: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.96)',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#492653',
    shadowOpacity: 0.1,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  backButton: { width: 46, height: 46, borderRadius: 16, backgroundColor: '#F5EEFA', alignItems: 'center', justifyContent: 'center' },
  headerCopy: { flex: 1, marginHorizontal: 12 },
  headerEyebrow: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.1, color: '#78B943' },
  headerTitle: { marginTop: 2, fontFamily: 'Jua', fontSize: 20, color: '#3E244C' },
  soonBadge: { paddingHorizontal: 9, paddingVertical: 8, borderRadius: 13, backgroundColor: '#F3E9FA', flexDirection: 'row', alignItems: 'center', gap: 5 },
  soonDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#8051C8' },
  soonText: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 0.7, color: '#8051C8' },
  scrollContent: { paddingHorizontal: 16, paddingBottom: 34, width: '100%', maxWidth: 700, alignSelf: 'center' },
  coachCard: { minHeight: 150, padding: 17, borderRadius: 28, backgroundColor: '#F1E5FA', flexDirection: 'row', alignItems: 'center', overflow: 'hidden' },
  sumi: { width: 112, height: 140, marginBottom: -15 },
  coachCopy: { flex: 1, marginLeft: 10 },
  coachKicker: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.1, color: '#8051C8' },
  coachTitle: { marginTop: 5, fontFamily: 'Jua', fontSize: 21, lineHeight: 26, color: '#3E244C' },
  coachText: { marginTop: 6, fontSize: 12, lineHeight: 18, color: '#746A79' },
  tabs: { marginTop: 14, padding: 5, borderRadius: 18, backgroundColor: '#FFFFFF', flexDirection: 'row' },
  tab: { flex: 1, minHeight: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  activeTab: { backgroundColor: '#8051C8' },
  tabText: { fontFamily: 'Jua', fontSize: 12, color: '#948897' },
  activeTabText: { color: '#FFFFFF' },
  loadingCard: { marginTop: 14, padding: 28, borderRadius: 24, backgroundColor: '#FFFFFF', alignItems: 'center' },
  loadingText: { marginTop: 10, fontSize: 12, color: '#837786' },
  statusCard: { marginTop: 14, padding: 17, borderRadius: 24, backgroundColor: '#FFFFFF', flexDirection: 'row' },
  statusIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#FCEAF1', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  statusCopy: { flex: 1 },
  statusLabel: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1, color: '#D64D82' },
  statusTitle: { marginTop: 3, fontFamily: 'Jua', fontSize: 17, color: '#3E244C' },
  statusText: { marginTop: 5, fontSize: 12, lineHeight: 18, color: '#7A6F7D' },
  primaryAction: { marginTop: 12, minHeight: 52, paddingHorizontal: 18, borderRadius: 18, backgroundColor: '#8051C8', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 },
  primaryActionText: { flex: 1, fontFamily: 'Jua', fontSize: 14, textAlign: 'center', color: '#FFFFFF' },
  emptyCard: { marginTop: 14, padding: 23, borderRadius: 24, backgroundColor: '#FFFFFF', alignItems: 'center' },
  emptyIcon: { width: 50, height: 50, borderRadius: 17, backgroundColor: '#F3EAF9', alignItems: 'center', justifyContent: 'center' },
  emptyTitle: { marginTop: 11, fontFamily: 'Jua', fontSize: 18, color: '#452A52' },
  emptyCopy: { marginTop: 5, maxWidth: 390, textAlign: 'center', fontSize: 12, lineHeight: 18, color: '#817583' },
  dataCard: { marginTop: 14, padding: 17, borderRadius: 24, backgroundColor: '#FFFFFF' },
  dataTitle: { marginBottom: 11, fontFamily: 'Jua', fontSize: 18, color: '#452A52' },
  noteRow: { marginTop: 8, padding: 11, borderRadius: 16, backgroundColor: '#F9F4FC', flexDirection: 'row', alignItems: 'center' },
  noteNumber: { width: 28, height: 28, borderRadius: 10, backgroundColor: '#8051C8', alignItems: 'center', justifyContent: 'center', marginRight: 9 },
  noteNumberText: { fontFamily: 'Jua', fontSize: 11, color: '#FFFFFF' },
  noteText: { flex: 1, fontSize: 12, lineHeight: 17, color: '#625666' },
  historyRow: { minHeight: 56, borderBottomWidth: 1, borderBottomColor: '#EEE7F1', flexDirection: 'row', alignItems: 'center' },
  historyIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#F3EAF9', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  historyTitle: { flex: 1, fontFamily: 'Jua', fontSize: 13, color: '#4D3458' },
  historyScore: { fontFamily: 'Jua', fontSize: 14, color: '#6AB53B' },
  progressLink: { marginTop: 14, padding: 14, borderRadius: 21, backgroundColor: '#F0F8EA', borderWidth: 1, borderColor: '#D4EAC5', flexDirection: 'row', alignItems: 'center' },
  progressIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', marginRight: 11 },
  progressCopy: { flex: 1 },
  progressTitle: { fontFamily: 'Jua', fontSize: 14, color: '#3D5D2C' },
  progressText: { marginTop: 2, fontSize: 10, lineHeight: 15, color: '#718268' },
});
