import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FBF8FE' },
  container: { flex: 1 },
  content: { paddingBottom: 120 },
  hero: { minHeight: 310, paddingHorizontal: 24, paddingTop: 18, overflow: 'hidden' },
  heroCircle: { position: 'absolute', width: 310, height: 310, borderRadius: 155, backgroundColor: '#EADAF9', right: -92, top: 22 },
  topRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { width: 48, height: 48, borderRadius: 15, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', shadowColor: '#48265F', shadowOpacity: 0.1, shadowRadius: 12, elevation: 4 },
  wordmark: { color: '#492858', fontSize: 11, fontWeight: '900', letterSpacing: 1.2 },
  heroCopy: { width: '58%', marginTop: 68, zIndex: 2 },
  eyebrow: { color: '#78C83F', fontSize: 10, fontWeight: '900', letterSpacing: 1.5 },
  title: { color: '#382044', fontSize: 30, lineHeight: 38, fontWeight: '400', fontFamily: 'Jua', marginTop: 8 },
  subtitle: { color: '#786B7D', fontSize: 13, lineHeight: 20, marginTop: 9 },
  mascot: { position: 'absolute', width: 185, height: 215, right: 5, bottom: 0 },
  body: { paddingHorizontal: 24, paddingTop: 22 },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  sectionTitle: { color: '#42264F', fontSize: 23, fontWeight: '400', fontFamily: 'Jua' },
  sectionSubtitle: { color: '#928698', fontSize: 12, marginTop: 4 },
  count: { color: '#61A934', backgroundColor: '#EEF8E7', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7, fontSize: 9, fontWeight: '900' },
  card: { minHeight: 142, borderRadius: 24, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E9E0ED', padding: 20, marginBottom: 14, flexDirection: 'row', alignItems: 'center', shadowColor: '#3E224B', shadowOpacity: 0.07, shadowRadius: 18, elevation: 3 },
  cardLocked: { opacity: 0.55, backgroundColor: '#F5F1F6' },
  icon: { width: 65, height: 65, borderRadius: 20, backgroundColor: '#F0E3FC', alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  iconGreen: { backgroundColor: '#EAF6E1' },
  cardCopy: { flex: 1 },
  cardLabel: { color: '#8423D9', fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  cardTitle: { color: '#43274F', fontSize: 21, lineHeight: 27, fontWeight: '400', fontFamily: 'Jua', marginTop: 6 },
  cardText: { color: '#8A7D90', fontSize: 12, lineHeight: 18, marginTop: 4 },
  action: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center' },
  actionDone: { backgroundColor: '#69B638' },
  modalBackdrop: { flex: 1, backgroundColor: '#29153599', justifyContent: 'center', padding: 24 },
  modalCard: { maxHeight: '82%', borderRadius: 28, backgroundColor: '#FFFFFF', padding: 25 },
  modalIcon: { width: 56, height: 56, borderRadius: 18, backgroundColor: '#F0E3FC', alignItems: 'center', justifyContent: 'center' },
  modalTitle: { color: '#40234C', fontSize: 26, fontWeight: '900', marginTop: 18 },
  modalText: { color: '#766A7B', fontSize: 13, lineHeight: 20, marginVertical: 14 },
  modalButton: { height: 52, borderRadius: 16, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center', marginTop: 10 },
  modalButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
});
