import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  background: { flex: 1, backgroundColor: '#FBF8FF' },
  container: { flex: 1, paddingHorizontal: 22, paddingTop: 48, paddingBottom: 24 },
  ambientCircle: { position: 'absolute', width: 330, height: 330, borderRadius: 165, backgroundColor: '#F0E3FF', top: -125, right: -120 },
  ambientLeaf: { position: 'absolute', width: 150, height: 150, borderRadius: 75, backgroundColor: '#EFF8E9', bottom: -35, left: -60, opacity: 0.8 },
  header: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 22, zIndex: 2 },
  backButtonContainer: { width: 52, height: 52, borderRadius: 17, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E9DDF2', justifyContent: 'center', alignItems: 'center', shadowColor: '#3D2052', shadowOpacity: 0.1, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  headerLabel: { flex: 1, paddingHorizontal: 10, color: '#552E68', fontSize: 10, fontWeight: '900', letterSpacing: 0.8, textAlign: 'center' },
  counterPill: { borderRadius: 18, backgroundColor: '#F0E4FA', paddingHorizontal: 13, paddingVertical: 8 },
  counterText: { color: '#8423D9', fontSize: 10, fontWeight: '900' },
  progressTrack: { height: 7, borderRadius: 7, backgroundColor: '#EDE6F0', overflow: 'hidden', marginBottom: 20 },
  progressFill: { height: '100%', borderRadius: 7, backgroundColor: '#8423D9' },
  contentContainer: { flex: 1, width: '100%', backgroundColor: '#FFFFFF', borderRadius: 34, borderWidth: 1, borderColor: '#E7D9ED', padding: 14, shadowColor: '#432653', shadowOpacity: 0.12, shadowRadius: 22, shadowOffset: { width: 0, height: 11 }, elevation: 6 },
  imageStage: { flex: 1, minHeight: 270, maxHeight: 400, borderRadius: 27, backgroundColor: '#F4ECFC', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 1, borderColor: '#E8D8F2' },
  imageAccent: { position: 'absolute', width: 190, height: 190, borderRadius: 95, backgroundColor: '#E7D2FA', right: -35, top: -42 },
  imageAccentSmall: { position: 'absolute', width: 90, height: 90, borderRadius: 45, backgroundColor: '#EAF5DF', left: -22, bottom: -18 },
  image: { width: '100%', height: '100%', resizeMode: 'cover' },
  wordContent: { alignItems: 'center', marginTop: 11, paddingTop: 14, paddingHorizontal: 10, paddingBottom: 3, borderRadius: 23, backgroundColor: '#FCFAFD' },
  categoryLabel: { color: '#63B934', fontSize: 9, fontWeight: '900', letterSpacing: 1.3, textTransform: 'uppercase', marginBottom: 7 },
  japanese: { fontSize: 37, fontFamily: 'Jua', fontWeight: '400', color: '#382046', lineHeight: 45, marginBottom: 1, textAlign: 'center' },
  romaji: { fontSize: 18, color: '#8423D9', fontFamily: 'Jua', marginBottom: 3 },
  english: { fontSize: 17, color: '#776B7D', marginBottom: 14, textAlign: 'center' },
  navigationContainer: { width: '100%', flexDirection: 'row', gap: 12, marginTop: 2 },
  nextButton: { flex: 1.25, minHeight: 54, paddingHorizontal: 18, backgroundColor: '#8423D9', borderRadius: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  previousButton: { flex: 0.8, backgroundColor: '#F1E8F7' },
  nextButtonText: { fontSize: 14, color: '#FFFFFF', fontWeight: '900', textAlign: 'center' },
  previousButtonText: { color: '#593269' },
  disabledButton: { opacity: 0.4 },
  noWordsText: { color: '#6E6075', fontSize: 16 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(39, 19, 51, 0.55)', alignItems: 'center', justifyContent: 'center', padding: 25 },
  completionCard: { width: '100%', maxWidth: 390, borderRadius: 32, backgroundColor: '#FFFFFF', padding: 26, alignItems: 'center', borderWidth: 1, borderColor: '#EADAF3' },
  completionArt: { width: 88, height: 88, borderRadius: 28, backgroundColor: '#EEE0FB', alignItems: 'center', justifyContent: 'center', marginBottom: 18 },
  completionEyebrow: { color: '#65B936', fontSize: 9, fontWeight: '900', letterSpacing: 1.2, marginBottom: 8 },
  completionTitle: { color: '#392047', fontFamily: 'Jua', fontWeight: '400', fontSize: 26, textAlign: 'center', marginBottom: 9 },
  completionCopy: { color: '#786C7F', fontSize: 15, lineHeight: 22, textAlign: 'center', marginBottom: 22 },
  completionButton: { width: '100%', minHeight: 56, borderRadius: 18, backgroundColor: '#8423D9', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 },
  completionButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
});
