import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');
const compact = height < 720;

export default StyleSheet.create({
  background: { flex: 1, width: '100%', height: '100%' },
  backgroundShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(35,15,49,0.22)' },
  safeArea: { flex: 1 },
  header: {
    marginHorizontal: 16,
    marginTop: 8,
    minHeight: 70,
    borderRadius: 25,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.96)',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#2A1437',
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  iconButton: { width: 46, height: 46, borderRadius: 16, backgroundColor: '#F5EEFA', alignItems: 'center', justifyContent: 'center' },
  headerCopy: { flex: 1, paddingHorizontal: 11 },
  headerEyebrow: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.2, color: '#65B83F' },
  headerTitle: { fontFamily: 'Jua', fontSize: 19, color: '#351A4A' },
  progressTrack: { height: 5, marginHorizontal: 30, marginTop: 10, borderRadius: 5, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,0.48)' },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: '#8B24E4' },
  storyStage: { flex: 1, overflow: 'hidden' },
  spriteStage: { ...StyleSheet.absoluteFillObject, top: compact ? 58 : 72, flexDirection: 'row', justifyContent: 'center', alignItems: 'flex-end' },
  spriteActor: { position: 'absolute', bottom: compact ? 116 : 136, height: compact ? height * 0.53 : height * 0.59, width: width * 0.68 },
  spriteLayer: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%' },
  primarySprite: { right: -width * 0.06, zIndex: 2 },
  secondarySprite: { left: -width * 0.15, zIndex: 1 },
  narrationWrap: { flex: 1, justifyContent: 'center', paddingHorizontal: 24 },
  narrationCard: { backgroundColor: 'rgba(28,14,37,0.9)', borderRadius: 30, padding: 26, borderWidth: 1, borderColor: 'rgba(255,255,255,0.42)', shadowColor: '#000000', shadowOpacity: 0.28, shadowRadius: 22, elevation: 11 },
  narrationLocation: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 99, paddingVertical: 7, paddingHorizontal: 11, backgroundColor: 'rgba(255,255,255,0.12)', marginBottom: 16 },
  narrationLocationText: { fontFamily: 'Jua', color: '#FFFFFF', fontSize: 11, letterSpacing: 0.5 },
  narrationRule: { width: 48, height: 4, borderRadius: 2, backgroundColor: '#7DDA47', marginBottom: 16 },
  narrationEyebrow: { fontFamily: 'Jua', color: '#A8EC7D', letterSpacing: 1.5, fontSize: 12, marginBottom: 10 },
  narrationText: { fontFamily: 'Jua', color: '#FFFFFF', fontSize: compact ? 19 : 22, lineHeight: compact ? 27 : 31 },
  continueRow: { marginTop: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 4 },
  continueText: { fontFamily: 'Jua', color: '#FFFFFF', fontSize: 12 },
  speechBubbleArea: { position: 'absolute', top: compact ? 22 : 34, width: '72%', zIndex: 20 },
  speechBubbleLeft: { left: 16 },
  speechBubbleRight: { right: 16 },
  speechBubble: { backgroundColor: 'rgba(255,255,255,0.98)', borderRadius: 24, paddingHorizontal: compact ? 15 : 18, paddingVertical: compact ? 13 : 16, borderWidth: 1, borderColor: 'rgba(132,35,217,0.14)', shadowColor: '#2C1738', shadowOpacity: 0.22, shadowRadius: 16, elevation: 10 },
  speechTail: { position: 'absolute', bottom: -9, width: 19, height: 19, backgroundColor: '#FFFFFF', transform: [{ rotate: '45deg' }] },
  speechTailLeft: { left: 54 },
  speechTailRight: { right: 54 },
  speakerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  speakerDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#62B83C', marginRight: 8 },
  speakerName: { fontFamily: 'Jua', fontSize: 14, color: '#4A265E', textTransform: 'uppercase', letterSpacing: 0.8 },
  nodeType: { marginLeft: 'auto', fontFamily: 'Jua', color: '#9B85A4', fontSize: 9 },
  dialogueJapanese: { fontFamily: 'Jua', fontSize: compact ? 21 : 25, color: '#351A4A', marginBottom: 2 },
  dialogueRomaji: { fontFamily: 'Jua', fontSize: 12, color: '#8423D9', marginBottom: 8 },
  dialogueText: { fontFamily: 'Jua', fontSize: compact ? 14 : 16, lineHeight: compact ? 20 : 23, color: '#5B4B61' },
  continueRowDark: { marginTop: 12, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 3 },
  continueTextDark: { fontFamily: 'Jua', fontSize: 11, color: '#8423D9' },
  decisionPanel: { position: 'absolute', left: 10, right: 10, bottom: 8, maxHeight: height * 0.46, borderRadius: 28, backgroundColor: 'rgba(250,248,251,0.985)', paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12, elevation: 14, shadowColor: '#281334', shadowOpacity: 0.22, shadowRadius: 18 },
  drawerHandle: { width: 46, height: 5, borderRadius: 5, alignSelf: 'center', backgroundColor: '#D8CFDA', marginBottom: 8 },
  decisionHeading: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  decisionIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center' },
  decisionEyebrow: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.4, color: '#65B83F' },
  decisionTitle: { fontFamily: 'Jua', fontSize: 19, color: '#351A4A' },
  decisionPrompt: { fontFamily: 'Jua', color: '#64536B', fontSize: 12, lineHeight: 16, marginVertical: 7 },
  choiceScroll: { maxHeight: compact ? 210 : 250 },
  choiceButton: { minHeight: 57, borderWidth: 1.5, borderColor: '#E6D9EB', backgroundColor: '#FFFFFF', borderRadius: 18, marginBottom: 7, paddingHorizontal: 10, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', shadowColor: '#432750', shadowOpacity: 0.07, shadowRadius: 8, elevation: 2 },
  choicePressed: { transform: [{ scale: 0.985 }], borderColor: '#8423D9', backgroundColor: '#FAF6FD' },
  choiceLetter: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#F1E5FA', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  choiceLetterText: { fontFamily: 'Jua', color: '#8423D9', fontSize: 15 },
  choiceCopy: { flex: 1 },
  choiceJapanese: { fontFamily: 'Jua', fontSize: 17, color: '#351A4A' },
  choiceRomaji: { fontFamily: 'Jua', fontSize: 10, color: '#8C6C97' },
  choiceEnglish: { display: 'none' },
  reactionAddress: { fontFamily: 'Jua', color: '#8423D9', fontSize: 14, marginBottom: 3 },
  inlineReactionRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 11 },
  inlineReactionDot: { width: 9, height: 9, borderRadius: 5 },
  inlineReactionLabel: { fontFamily: 'Jua', fontSize: 12 },
  reactionTeaching: { fontFamily: 'Jua', color: '#65566B', fontSize: 12, lineHeight: 18, marginTop: 7 },
  inlineCultureNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 7, borderRadius: 14, padding: 10, backgroundColor: '#F1F8EC', marginTop: 9 },
  inlineCultureText: { flex: 1, fontFamily: 'Jua', color: '#4E6840', fontSize: 11, lineHeight: 16 },
  endingCard: { margin: 22, marginTop: 'auto', marginBottom: 'auto', borderRadius: 30, backgroundColor: 'rgba(255,255,255,0.97)', padding: 28, alignItems: 'center' },
  endingEyebrow: { fontFamily: 'Jua', fontSize: 10, color: '#65B83F', letterSpacing: 1.5, marginTop: 12 },
  endingTitle: { fontFamily: 'Jua', color: '#351A4A', fontSize: 26, textAlign: 'center', marginVertical: 8 },
  endingText: { fontFamily: 'Jua', color: '#706475', fontSize: 15, textAlign: 'center', marginBottom: 10 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(25,12,34,0.7)', alignItems: 'center', justifyContent: 'center', padding: 20 },
  feedbackCard: { width: '100%', maxWidth: 480, maxHeight: '90%', borderRadius: 30, backgroundColor: '#FFFFFF', padding: 22, alignItems: 'center' },
  feedbackIcon: { width: 60, height: 60, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  feedbackEyebrow: { fontFamily: 'Jua', letterSpacing: 1.2, fontSize: 11 },
  feedbackReaction: { fontFamily: 'Jua', fontSize: 20, lineHeight: 27, textAlign: 'center', color: '#351A4A', marginVertical: 10 },
  explanationBox: { width: '100%', backgroundColor: '#F8F3FA', borderRadius: 18, padding: 14, marginTop: 6 },
  explanationLabel: { fontFamily: 'Jua', color: '#8423D9', fontSize: 9, letterSpacing: 1 },
  explanationText: { fontFamily: 'Jua', color: '#64576A', fontSize: 13, lineHeight: 19, marginTop: 5 },
  cultureBox: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', gap: 9, backgroundColor: '#F1F9EC', borderRadius: 18, padding: 13, marginTop: 10 },
  cultureText: { flex: 1, fontFamily: 'Jua', color: '#4E6642', fontSize: 12, lineHeight: 18 },
  primaryButton: { minHeight: 50, marginTop: 14, borderRadius: 17, backgroundColor: '#8423D9', paddingHorizontal: 22, alignSelf: 'stretch', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  primaryButtonText: { fontFamily: 'Jua', color: '#FFFFFF', fontSize: 15 },
  secondaryButton: { minHeight: 48, marginTop: 9, borderRadius: 17, backgroundColor: '#F4ECF8', alignSelf: 'stretch', alignItems: 'center', justifyContent: 'center' },
  secondaryButtonText: { fontFamily: 'Jua', color: '#5A376B', fontSize: 14 },
  exitCard: { width: '100%', maxWidth: 430, borderRadius: 30, backgroundColor: '#FFFFFF', padding: 24, alignItems: 'center' },
  exitTitle: { fontFamily: 'Jua', color: '#351A4A', fontSize: 24, marginTop: 10 },
  exitText: { fontFamily: 'Jua', color: '#746779', textAlign: 'center', fontSize: 14, lineHeight: 20, marginTop: 8 },
  loadingScreen: { flex: 1, backgroundColor: '#FAF7FC', alignItems: 'center', justifyContent: 'center', padding: 28 },
  loadingMascot: { width: 120, height: 140, resizeMode: 'contain', marginBottom: 10 },
  loadingTitle: { fontFamily: 'Jua', color: '#351A4A', fontSize: 24, textAlign: 'center', marginTop: 14 },
  loadingText: { fontFamily: 'Jua', color: '#87798B', fontSize: 14, textAlign: 'center', marginTop: 6 },
  textButtonWrap: { padding: 15 },
  textButton: { fontFamily: 'Jua', color: '#8423D9', fontSize: 14, textAlign: 'center', marginTop: 14 },
  resultsPage: { flex: 1, backgroundColor: '#F8F2FC' },
  resultsContent: { padding: 24, alignItems: 'center' },
  resultMedal: { width: 78, height: 78, borderRadius: 27, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  resultsEyebrow: { fontFamily: 'Jua', color: '#64B83E', fontSize: 11, letterSpacing: 1.4, marginTop: 18 },
  resultsTitle: { fontFamily: 'Jua', color: '#351A4A', fontSize: 25, textAlign: 'center', marginTop: 4 },
  resultsScore: { fontFamily: 'Jua', color: '#8423D9', fontSize: 58, marginTop: 10 },
  resultsRating: { fontFamily: 'Jua', color: '#726576', fontSize: 14, textAlign: 'center' },
  resultGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: 18 },
  resultTile: { width: '48%', borderRadius: 20, backgroundColor: '#FFFFFF', padding: 16, marginBottom: 10, alignItems: 'center' },
  resultDot: { width: 9, height: 9, borderRadius: 5 },
  resultValue: { fontFamily: 'Jua', color: '#351A4A', fontSize: 27, marginTop: 5 },
  resultLabel: { fontFamily: 'Jua', color: '#827585', fontSize: 11 },
  reviewPage: { flex: 1, backgroundColor: '#FAF7FC' },
  reviewHeader: { padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#EEE2F2' },
  reviewEyebrow: { fontFamily: 'Jua', color: '#63B63C', fontSize: 9, letterSpacing: 1.2 },
  reviewTitle: { fontFamily: 'Jua', color: '#351A4A', fontSize: 21 },
  reviewContent: { padding: 16, paddingBottom: 40 },
  reviewCard: { backgroundColor: '#FFFFFF', borderRadius: 22, padding: 17, marginBottom: 12, borderWidth: 1, borderColor: '#EADFED' },
  reviewCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  reviewNumber: { fontFamily: 'Jua', fontSize: 9, color: '#9B89A1', letterSpacing: 1 },
  reviewEvaluation: { fontFamily: 'Jua', fontSize: 11 },
  reviewPrompt: { fontFamily: 'Jua', color: '#4F3A58', fontSize: 14, marginTop: 10 },
  reviewSelected: { fontFamily: 'Jua', color: '#351A4A', fontSize: 20, marginTop: 9 },
  reviewEnglish: { fontFamily: 'Jua', color: '#857789', fontSize: 12 },
  bestAnswerBox: { backgroundColor: '#F1F9EC', borderRadius: 14, padding: 10, marginTop: 10 },
  bestAnswerLabel: { fontFamily: 'Jua', color: '#5FAA38', fontSize: 9, letterSpacing: 1 },
  bestAnswerText: { fontFamily: 'Jua', color: '#43573A', fontSize: 13, marginTop: 3 },
  reviewExplanation: { fontFamily: 'Jua', color: '#6D6071', fontSize: 12, lineHeight: 18, marginTop: 10 },
  reviewCulture: { fontFamily: 'Jua', color: '#8423D9', fontSize: 11, lineHeight: 17, marginTop: 8 },
  emptyReview: { alignItems: 'center', padding: 35 },
  emptyReviewTitle: { fontFamily: 'Jua', color: '#351A4A', fontSize: 20, marginTop: 12 },
  emptyReviewText: { fontFamily: 'Jua', color: '#847789', fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 6 },
});
