import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screenBackground: {
    flex: 1,
    backgroundColor: '#FBF8FE',
  },
  header: {
    minHeight: 82,
    paddingTop: 22,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  backButtonContainer: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E4D9EA',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#462A5E',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  completedBadge: {
    minHeight: 40,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F1F9EB',
    borderWidth: 1,
    borderColor: '#D5ECC5',
  },
  completedBadgeTitle: {
    color: '#57982F',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  completedBadgeText: {
    marginTop: 2,
    color: '#718164',
    fontSize: 9,
  },
  container: { flex: 1, padding: 16, backgroundColor: '#FBF8FE' },
  characterDisplay: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  romaji: { fontSize: 48, marginBottom: 20, fontFamily: 'Jua', color: '#442451' },
  character: { fontSize: 32, marginBottom: 20, color: '#442451' },
  button: { padding: 15, backgroundColor: '#8423D9', borderRadius: 16, marginVertical: 10, minWidth: 100, justifyContent: 'center', alignItems: 'center' },
  buttonText: { color: '#FFFFFF', fontSize: 18 },
  matchGame: {
    flex: 1,
    marginHorizontal: 14,
    marginBottom: 12,
    paddingTop: 0,
    paddingHorizontal: 0,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: '#E8DEED',
    shadowColor: '#442451',
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
    overflow: 'hidden',
  },
  matchGameContent: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 10,
  },
  gameHero: {
    width: '100%',
    minHeight: 122,
    paddingHorizontal: 18,
    paddingVertical: 14,
    overflow: 'hidden',
  },
  gameHeroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  gameModePill: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  gameModeText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  roundPill: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#B8EF88',
  },
  roundPillText: {
    color: '#447923',
    fontSize: 8,
    fontWeight: '900',
  },
  gameHeroTitle: {
    marginTop: 13,
    color: '#FFFFFF',
    fontSize: 23,
    lineHeight: 27,
    fontFamily: 'Jua',
  },
  gameHeroText: {
    width: '88%',
    marginTop: 3,
    color: '#EBDCF7',
    fontSize: 10,
    lineHeight: 14,
  },
  heroKana: {
    position: 'absolute',
    color: 'rgba(255,255,255,0.10)',
    fontSize: 82,
    fontFamily: 'Jua',
  },
  heroKanaLeft: { left: -18, bottom: -42, transform: [{ rotate: '-12deg' }] },
  heroKanaRight: { right: -8, top: 30, transform: [{ rotate: '10deg' }] },
  roundDots: {
    position: 'absolute',
    left: 18,
    bottom: 9,
    flexDirection: 'row',
    gap: 5,
  },
  roundDot: {
    width: 18,
    height: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  roundDotActive: {
    width: 30,
    backgroundColor: '#B8EF88',
  },
  matchGameText: {
    width: '90%',
    marginTop: 10,
    marginBottom: 9,
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderRadius: 14,
    backgroundColor: '#F3EAFB',
    color: '#432650',
    fontSize: 16,
    lineHeight: 21,
    fontFamily: 'Jua',
    textAlign: 'center',
  },
  cardsContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 10,
    paddingBottom: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignContent: 'center',
    gap: 6,
  },
  card: {
    width: '27%',
    maxWidth: 88,
    minWidth: 58,
    height: '27%',
    maxHeight: 94,
    minHeight: 68,
    margin: 3,
    borderRadius: 17,
    overflow: 'hidden',
    backgroundColor: '#882BDD',
    borderWidth: 2,
    borderColor: '#F0DFFE',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#592172',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 5,
  },
  cardText: { fontSize: 31, color: '#FFFFFF', fontFamily: 'Jua' },
  cardImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  messageContainer: {
    position: 'absolute',
    zIndex: 10,
    top: '24%',
    left: 18,
    right: 18,
    padding: 25,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DFD3E5',
    alignItems: 'center',
    shadowColor: '#32153F',
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 12,
  },
  message: { color: '#579C31', fontSize: 23, fontFamily: 'Jua', marginBottom: 18, textAlign: 'center' },
  nextButton: { minWidth: 180, minHeight: 52, paddingHorizontal: 22, borderRadius: 17, backgroundColor: '#8423D9', justifyContent: 'center', alignItems: 'center' },
  nextButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800', textAlign: 'center' },
  completionOverlay: {
    position: 'absolute',
    zIndex: 20,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    padding: 18,
    justifyContent: 'center',
    backgroundColor: 'rgba(45, 24, 55, 0.48)',
  },
  completionCard: {
    padding: 27,
    borderRadius: 30,
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5D9EB',
    shadowColor: '#2E1738',
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 14,
  },
  completionIconRing: {
    width: 90,
    height: 90,
    borderRadius: 45,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF8E8',
    borderWidth: 1,
    borderColor: '#D7EEC7',
  },
  completionIcon: {
    width: 66,
    height: 66,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6CB63A',
    shadowColor: '#6CB63A',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 6,
  },
  completionSpark: {
    position: 'absolute',
    color: '#A861E1',
    fontSize: 25,
  },
  sparkLeft: { top: 35, left: 48, transform: [{ rotate: '-15deg' }] },
  sparkRight: { top: 58, right: 48, color: '#8ACD50', transform: [{ rotate: '15deg' }] },
  completionEyebrow: {
    marginTop: 20,
    color: '#66A936',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.3,
  },
  completionTitle: {
    marginTop: 7,
    color: '#40234D',
    fontSize: 29,
    lineHeight: 35,
    fontFamily: 'Jua',
  },
  completionText: {
    maxWidth: 320,
    marginTop: 9,
    color: '#7B6E81',
    fontSize: 12,
    lineHeight: 19,
    textAlign: 'center',
  },
  completionSaved: {
    width: '100%',
    marginTop: 20,
    padding: 13,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#F2F8ED',
  },
  completionSavedText: {
    flex: 1,
    color: '#637457',
    fontSize: 10,
    lineHeight: 15,
  },
  completionButton: {
    width: '100%',
    minHeight: 55,
    marginTop: 18,
    paddingHorizontal: 20,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    backgroundColor: '#8423D9',
  },
  completionButtonPressed: { opacity: 0.84, transform: [{ scale: 0.98 }] },
  completionButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
});

export default styles;
