import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F1FA',
  },
  background: {
    flex: 1,
  },
  sceneTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(53,32,58,0.2)',
  },
  header: {
    marginHorizontal: 16,
    marginTop: 14,
    minHeight: 78,
    paddingHorizontal: 12,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.96)',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#3D2448',
    shadowOpacity: 0.13,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 7,
    zIndex: 20,
  },
  headerButton: {
    width: 48,
    height: 48,
    borderRadius: 17,
    backgroundColor: '#F5EFF8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCopy: {
    flex: 1,
    marginHorizontal: 12,
  },
  headerEyebrow: {
    fontFamily: 'Jua',
    fontSize: 9,
    letterSpacing: 1.15,
  },
  headerTitle: {
    marginTop: 2,
    fontFamily: 'Jua',
    fontSize: 21,
    color: '#3C2348',
  },
  stage: {
    flex: 1,
    alignItems: 'center',
    overflow: 'hidden',
  },
  stageHalo: {
    position: 'absolute',
    top: '3%',
    width: Math.min(width * 0.82, 490),
    aspectRatio: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(239,224,248,0.44)',
  },
  coachStatus: {
    position: 'absolute',
    top: 18,
    zIndex: 7,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.94)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    shadowColor: '#3D2448',
    shadowOpacity: 0.1,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  onlineDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#65B23C',
  },
  coachStatusText: {
    fontFamily: 'Jua',
    fontSize: 9,
    letterSpacing: 0.8,
    color: '#56365F',
  },
  sumi: {
    position: 'absolute',
    top: '4%',
    width: Math.min(width * 0.76, 460),
    height: '52%',
    zIndex: 3,
  },
  floorShadow: {
    position: 'absolute',
    top: '49%',
    width: Math.min(width * 0.55, 320),
    height: 24,
    borderRadius: 999,
    backgroundColor: 'rgba(47,30,51,0.2)',
    zIndex: 1,
  },
  floorLine: {
    position: 'absolute',
    top: '50%',
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  controlPanel: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    padding: 16,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.97)',
    shadowColor: '#3B2245',
    shadowOpacity: 0.18,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 9 },
    elevation: 10,
    zIndex: 10,
  },
  promptRow: {
    paddingBottom: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE8F1',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  promptIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  promptCopy: {
    flex: 1,
  },
  promptLabel: {
    fontFamily: 'Jua',
    fontSize: 9,
    letterSpacing: 1.05,
  },
  promptTitle: {
    marginTop: 3,
    fontFamily: 'Jua',
    fontSize: 16,
    lineHeight: 21,
    color: '#40264B',
  },
  promptNote: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 16,
    color: '#887B8C',
  },
  languageRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  languageLabel: {
    fontFamily: 'Jua',
    fontSize: 9,
    letterSpacing: 0.9,
    color: '#837687',
  },
  languageSelector: {
    padding: 4,
    borderRadius: 15,
    backgroundColor: '#F5F0F7',
    flexDirection: 'row',
  },
  languageChoice: {
    minWidth: 72,
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  languageChoiceText: {
    fontFamily: 'Jua',
    fontSize: 11,
    color: '#877A8B',
  },
  languageChoiceTextActive: {
    color: '#FFFFFF',
  },
  microphoneArea: {
    marginTop: 12,
    alignItems: 'center',
  },
  microphoneButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 5,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4A2857',
    shadowOpacity: 0.24,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  microphonePressed: {
    transform: [{ scale: 0.96 }],
  },
  microphoneStatus: {
    marginTop: 7,
    minHeight: 17,
    textAlign: 'center',
    fontFamily: 'Jua',
    fontSize: 11,
    color: '#58425F',
  },
  secondaryActions: {
    marginTop: 11,
    flexDirection: 'row',
    gap: 9,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 43,
    paddingHorizontal: 10,
    borderRadius: 15,
    backgroundColor: '#F7F2F9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  secondaryButtonText: {
    fontFamily: 'Jua',
    fontSize: 11,
    color: '#5B4563',
  },
  tutorialShade: {
    flex: 1,
    padding: 20,
    backgroundColor: 'rgba(40,23,47,0.58)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tutorialCard: {
    width: '100%',
    maxWidth: 480,
    padding: 19,
    borderRadius: 29,
    backgroundColor: '#FFFFFF',
    shadowColor: '#24122B',
    shadowOpacity: 0.25,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  tutorialHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 9,
  },
  tutorialIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  tutorialHeaderCopy: {
    flex: 1,
  },
  tutorialKicker: {
    fontFamily: 'Jua',
    fontSize: 9,
    letterSpacing: 1,
  },
  tutorialTitle: {
    marginTop: 2,
    fontFamily: 'Jua',
    fontSize: 22,
    color: '#40264B',
  },
  tutorialClose: {
    width: 39,
    height: 39,
    borderRadius: 13,
    backgroundColor: '#F6F1F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tutorialStep: {
    marginTop: 10,
    padding: 11,
    borderRadius: 17,
    backgroundColor: '#FAF7FC',
    flexDirection: 'row',
    alignItems: 'center',
  },
  tutorialStepNumber: {
    width: 33,
    height: 33,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  tutorialStepNumberText: {
    fontFamily: 'Jua',
    fontSize: 12,
    color: '#FFFFFF',
  },
  tutorialStepCopy: {
    flex: 1,
  },
  tutorialStepTitle: {
    fontFamily: 'Jua',
    fontSize: 14,
    color: '#43284F',
  },
  tutorialStepText: {
    marginTop: 2,
    fontSize: 11,
    lineHeight: 16,
    color: '#7E7282',
  },
  tutorialNotice: {
    marginTop: 13,
    padding: 11,
    borderRadius: 16,
    backgroundColor: '#FFF7E8',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  tutorialNoticeText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 16,
    color: '#7B603D',
  },
  tutorialDone: {
    marginTop: 14,
    minHeight: 49,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tutorialDoneText: {
    fontFamily: 'Jua',
    fontSize: 15,
    color: '#FFFFFF',
  },
});
