import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#FCFAFF' },
    container: {
        flex: 1,
        minHeight: 0,
        backgroundColor: '#FCFAFF',
        overflow: 'hidden',
    },
    scrollView: { flex: 1 },
    background: {
        flex: 1,
        resizeMode: 'cover',
    },
    scrollContent: { paddingBottom: 112 },
    header: { minHeight: 390, paddingHorizontal: 20, paddingTop: 14, backgroundColor: '#FBF8FF', overflow: 'hidden' },
    heroCircle: { position: 'absolute', width: 295, height: 295, borderRadius: 148, right: -55, top: 66, backgroundColor: '#EEE2FA' },
    heroCloudOne: { position: 'absolute', width: 62, height: 20, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.72)', right: 248, top: 180 },
    heroCloudTwo: { position: 'absolute', width: 46, height: 16, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.64)', right: 145, top: 147 },
    heroFuji: { position: 'absolute', right: 5, bottom: 16, width: 0, height: 0, borderLeftWidth: 105, borderRightWidth: 105, borderBottomWidth: 142, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: 'rgba(132,35,217,0.08)' },
    heroFujiSnow: { position: 'absolute', right: 65, bottom: 102, width: 0, height: 0, borderLeftWidth: 45, borderRightWidth: 45, borderBottomWidth: 55, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: 'rgba(255,255,255,0.68)' },
    headerTopRow: { flexDirection: 'row', alignItems: 'center', zIndex: 5 },
    backButtonContainer: {
        height: 44, width: 44, borderRadius: 15,
        backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EDE5F1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    pressed: { opacity: 0.72 },
    headerWordmark: { flexDirection: 'row', alignItems: 'center', gap: 6, marginLeft: 11 },
    headerWordmarkText: { color: '#4A3158', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
    headerIcon: { marginLeft: 'auto', width: 44, height: 44, borderRadius: 15, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EDE5F1', alignItems: 'center', justifyContent: 'center', shadowColor: '#462A5E', shadowOpacity: 0.10, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
    heroBody: { flex: 1, flexDirection: 'row', alignItems: 'center', paddingTop: 5 },
    heroCopy: { width: '52%', zIndex: 4 },
    heroEyebrow: { color: '#8ED94D', fontSize: 9, fontWeight: '900', letterSpacing: 1.4, marginBottom: 5 },
    headerTitle: { color: '#2F193D', fontFamily: 'Jua', fontSize: 25, lineHeight: 30 },
    headerSubtitle: { color: '#655A6C', fontSize: 11, lineHeight: 17, marginTop: 6, maxWidth: 190 },
    mascotStage: { width: '48%', height: 285, alignItems: 'center', justifyContent: 'flex-end', alignSelf: 'flex-end', zIndex: 3 },
    mascotSun: { position: 'absolute', width: 218, height: 218, borderRadius: 109, backgroundColor: 'rgba(224,203,246,0.72)', bottom: 8, right: -20 },
    mascotGround: { position: 'absolute', width: 175, height: 27, borderRadius: 14, backgroundColor: 'rgba(132,35,217,0.11)', bottom: 5, right: -1 },
    mascotImage: { width: 190, height: 248, zIndex: 2 },
    contentBody: { paddingHorizontal: 20 },
    dialogueSteps: { flexDirection: 'row', gap: 5, marginTop: 14 },
    dialogueStep: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#DDD4E1' },
    dialogueStepActive: { width: 18, backgroundColor: '#8423D9' },
    sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 25, marginBottom: 14 },
    sectionTitle: { color: '#382044', fontFamily: 'Jua', fontSize: 22 },
    sectionSubtitle: { color: '#837787', fontSize: 11, marginTop: 2 },
    activityCount: { backgroundColor: '#EFF8E8', borderRadius: 99, paddingHorizontal: 9, paddingVertical: 6 },
    activityCountText: { color: '#5A9E36', fontSize: 8, fontWeight: '900', letterSpacing: 0.8 },
    featuredCard: { minHeight: 128, borderRadius: 24, padding: 17, backgroundColor: '#8423D9', flexDirection: 'row', alignItems: 'center', overflow: 'hidden', borderBottomWidth: 5, borderBottomColor: '#6417A6', shadowColor: '#4B1B63', shadowOpacity: 0.17, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 6 },
    featuredCharacter: { position: 'absolute', right: 37, bottom: -34, color: 'rgba(255,255,255,0.08)', fontFamily: 'Jua', fontSize: 112 },
    featuredIcon: { width: 55, height: 55, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center', marginRight: 14 },
    featuredCopy: { flex: 1 },
    featuredEyebrow: { color: '#CFF3B6', fontSize: 8, fontWeight: '900', letterSpacing: 1.2 },
    featuredTitle: { color: '#FFFFFF', fontFamily: 'Jua', fontSize: 21, marginTop: 2 },
    featuredSubtitle: { color: '#EADAF5', fontSize: 11, marginTop: 2 },
    featuredPlay: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
    featuredInfo: { position: 'absolute', right: 11, top: 10, width: 29, height: 29, alignItems: 'center', justifyContent: 'center' },
    cardPressed: { opacity: 0.86, transform: [{ scale: 0.99 }] },
    activityGrid: { marginTop: 14 },
    activityCard: { width: '100%', height: 238, borderRadius: 25, marginBottom: 16, overflow: 'hidden', backgroundColor: '#321645', shadowColor: '#321645', shadowOpacity: 0.20, shadowRadius: 15, shadowOffset: { width: 0, height: 8 }, elevation: 7 },
    cardCover: { width: '100%', height: '100%', padding: 17, justifyContent: 'space-between' },
    cardCoverImage: { width: '100%', height: '100%', borderRadius: 25 },
    cardShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(20,7,30,0.04)', borderRadius: 25 },
    cardTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    cardTag: { minHeight: 31, paddingHorizontal: 11, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.94)', flexDirection: 'row', alignItems: 'center', gap: 6 },
    cardTagText: { fontSize: 8, fontWeight: '900', letterSpacing: 0.9 },
    infoButton: { width: 34, height: 34, borderRadius: 12, backgroundColor: 'rgba(31,13,43,0.34)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)' },
    cardCopy: { maxWidth: '66%', marginTop: 'auto', marginBottom: 12 },
    activityTitle: { color: '#FFFFFF', fontFamily: 'Jua', fontSize: 25, textShadowColor: 'rgba(29,8,41,0.42)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 5 },
    activitySubtitle: { color: 'rgba(255,255,255,0.92)', fontSize: 11, lineHeight: 16, marginTop: 3 },
    activityFooter: { minHeight: 45, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.22)', paddingTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    playOverline: { color: 'rgba(255,255,255,0.72)', fontSize: 7, fontWeight: '900', letterSpacing: 1.1 },
    playLabel: { color: '#FFFFFF', fontSize: 10, fontWeight: '900', letterSpacing: 0.35, marginTop: 1 },
    smallPlay: { width: 38, height: 38, borderRadius: 13, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', shadowColor: '#24112D', shadowOpacity: 0.18, shadowRadius: 8, elevation: 3 },
    tipCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFDF6', borderWidth: 1, borderColor: '#F4E5B8', borderRadius: 19, padding: 14, marginTop: 2 },
    tipIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFF1C8', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
    tipCopy: { flex: 1 }, tipLabel: { color: '#8B621C', fontSize: 11, fontWeight: '900' }, tipText: { color: '#77694D', fontSize: 11, lineHeight: 16, marginTop: 2 },
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(32,18,40,0.58)', alignItems: 'center', justifyContent: 'center', padding: 24 },
    modalCard: { width: '100%', maxWidth: 360, borderRadius: 26, backgroundColor: '#FFFFFF', padding: 24, alignItems: 'center' },
    modalIcon: { width: 58, height: 58, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 15 },
    modalEyebrow: { color: '#8ED94D', fontSize: 9, fontWeight: '900', letterSpacing: 1.3 }, modalTitle: { color: '#382044', fontFamily: 'Jua', fontSize: 24, marginTop: 4 },
    modalText: { color: '#766B7C', fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 8 },
    modalButton: { width: '100%', height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, modalButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
    darkPage: { backgroundColor: '#120D17' },
    darkHeader: { backgroundColor: '#1B1223' },
    darkTitle: { color: '#F6EFFA' },
    darkMuted: { color: '#B9ACBF' },
    darkTip: { backgroundColor: '#282016', borderColor: '#5B4724' },
});

export default styles;
