import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FBF9FD' },
  container: { flex: 1, overflow: 'hidden', backgroundColor: '#FBF9FD' },
  content: { flex: 1, width: '100%', maxWidth: 620, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 24, paddingBottom: 20 },
  decorativeCircle: { position: 'absolute', width: 390, height: 390, borderRadius: 195, right: -205, top: 100, backgroundColor: '#F0E2FA' },
  decorativeCircleSmall: { position: 'absolute', width: 180, height: 180, borderRadius: 90, left: -115, bottom: 20, backgroundColor: '#EAF5E3' },
  cloudOne: { position: 'absolute', width: 82, height: 16, borderRadius: 20, right: 25, top: 188, backgroundColor: 'rgba(255,255,255,.76)' },
  cloudTwo: { position: 'absolute', width: 54, height: 13, borderRadius: 18, right: 105, top: 216, backgroundColor: 'rgba(255,255,255,.68)' },
  brandRow: { flexDirection: 'row', alignItems: 'center' },
  logoPlate: { width: 54, height: 54, borderRadius: 17, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center', marginRight: 12, shadowColor: '#5D168F', shadowOpacity: .2, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  appLogo: { width: 44, height: 44, borderRadius: 13 },
  brandName: { color: '#2E193C', fontSize: 20, fontWeight: '900', letterSpacing: .8 },
  brandSubtitle: { color: '#75667D', fontSize: 10, marginTop: 2 },
  hero: { flex: 1, minHeight: 310, alignItems: 'center', justifyContent: 'center', paddingTop: 8 },
  heroCopy: { alignItems: 'center', zIndex: 3, marginTop: 12 },
  eyebrow: { color: '#65A936', fontSize: 12, fontWeight: '800', letterSpacing: 2 },
  title: { color: '#342040', fontFamily: 'Jua', fontSize: 31, lineHeight: 38, marginTop: 8, textAlign: 'center' },
  subtitle: { color: '#776A7C', fontSize: 13, marginTop: 5, letterSpacing: .4 },
  mascotScene: { width: 260, height: 270, alignItems: 'center', justifyContent: 'flex-end' },
  mascotHalo: { position: 'absolute', width: 230, height: 230, borderRadius: 115, bottom: 7, backgroundColor: 'rgba(224,196,246,.68)', borderWidth: 1, borderColor: 'rgba(255,255,255,.78)' },
  mascot: { width: 190, height: 228, zIndex: 3, marginBottom: 3 },
  mascotGround: { position: 'absolute', width: 188, height: 20, borderRadius: 10, bottom: 0, backgroundColor: 'rgba(132,35,217,.11)' },
  actions: { gap: 10 },
  primaryButton: { height: 58, borderRadius: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#8423D9', borderBottomWidth: 5, borderBottomColor: '#6515A8', shadowColor: '#6420A0', shadowOpacity: .2, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  primaryButtonText: { color: '#FFF', fontFamily: 'Jua', fontSize: 17 },
  primaryArrow: { position: 'absolute', right: 12, width: 35, height: 35, borderRadius: 12, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  secondaryButton: { height: 54, borderRadius: 18, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#DDD0E4' },
  secondaryButtonText: { color: '#593F66', fontFamily: 'Jua', fontSize: 14 },
  buttonPressed: { opacity: .82, transform: [{ scale: .99 }] },
  footerText: { color: '#9A8EA0', fontSize: 9, textAlign: 'center', marginTop: 12 },
});

export default styles;
