import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8F3FB' },
  background: { flex: 1 },
  overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(248,244,250,0.88)' },
  header: {
    marginHorizontal: 18,
    marginTop: 12,
    marginBottom: 11,
    minHeight: 72,
    paddingHorizontal: 10,
    borderRadius: 23,
    backgroundColor: 'rgba(255,255,255,0.96)',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#492653',
    shadowOpacity: 0.1,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  backButton: { width: 44, height: 44, borderRadius: 15, backgroundColor: '#F5EEFA', alignItems: 'center', justifyContent: 'center' },
  headerCopy: { flex: 1, marginLeft: 12, marginRight: 8 },
  headerEyebrow: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 1, color: '#78B943' },
  headerTitle: { marginTop: 2, fontFamily: 'Jua', fontSize: 20, color: '#3E244C' },
  roomBadge: { maxWidth: 112, paddingHorizontal: 9, paddingVertical: 8, borderRadius: 13, backgroundColor: '#F3E9FA', flexDirection: 'row', alignItems: 'center', gap: 5 },
  roomBadgeText: { flexShrink: 1, fontFamily: 'Jua', fontSize: 9, color: '#8051C8' },
  scrollContent: { paddingHorizontal: 18, paddingBottom: 34, width: '100%', maxWidth: 700, alignSelf: 'center' },
  coachCard: { minHeight: 190, paddingRight: 16, borderRadius: 30, backgroundColor: '#40224F', flexDirection: 'row', alignItems: 'center', overflow: 'hidden', shadowColor: '#3C2049', shadowOpacity: 0.2, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
  heroOrbLarge: { position: 'absolute', left: -48, bottom: -65, width: 230, height: 230, borderRadius: 115, backgroundColor: '#7440A0' },
  heroOrbSmall: { position: 'absolute', right: -38, top: -52, width: 145, height: 145, borderRadius: 73, backgroundColor: 'rgba(216,79,131,0.2)' },
  sumi: { width: Math.min(width * 0.36, 170), height: 188, alignSelf: 'flex-end', zIndex: 2 },
  coachCopy: { flex: 1, marginLeft: 3, zIndex: 3 },
  coachKickerRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#8CDC54' },
  coachKicker: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.1, color: '#A8E57E' },
  coachTitle: { marginTop: 6, fontFamily: 'Jua', fontSize: 20, lineHeight: 25, color: '#FFFFFF' },
  coachText: { marginTop: 6, fontSize: 11, lineHeight: 16, color: '#DCCFE0' },
  heroStatus: { marginTop: 10, alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.11)', flexDirection: 'row', alignItems: 'center', gap: 5 },
  heroStatusText: { flexShrink: 1, fontSize: 8, color: '#F4EAF6' },
  tabs: { marginTop: 14, padding: 5, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.97)', borderWidth: 1, borderColor: '#E9DFED', flexDirection: 'row', shadowColor: '#462551', shadowOpacity: 0.07, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  tab: { flex: 1, minHeight: 43, borderRadius: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  activeTab: { backgroundColor: '#8051C8' },
  tabText: { fontFamily: 'Jua', fontSize: 10, color: '#8E8093' },
  activeTabText: { color: '#FFFFFF' },
  loadingCard: { marginTop: 14, padding: 28, borderRadius: 24, backgroundColor: '#FFFFFF', alignItems: 'center' },
  loadingText: { marginTop: 10, fontSize: 12, color: '#837786' },
  sectionHeading: { marginTop: 19, marginBottom: 10, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  sectionKicker: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 1.1, color: '#68AE3B' },
  sectionTitle: { marginTop: 3, fontFamily: 'Jua', fontSize: 19, color: '#43274F' },
  readyBadge: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 13, backgroundColor: '#EDF7E7', flexDirection: 'row', alignItems: 'center', gap: 5 },
  readyDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#62B335' },
  readyText: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 0.8, color: '#559D30' },
  statusGrid: { flexDirection: 'row', gap: 10 },
  featureCard: { flex: 1, minHeight: 164, padding: 14, borderRadius: 23, borderWidth: 1 },
  featureCardPurple: { backgroundColor: '#F5EEFB', borderColor: '#E5D5F2' },
  featureCardPink: { backgroundColor: '#FFF1F6', borderColor: '#F3D8E4' },
  featureIconPurple: { width: 42, height: 42, marginBottom: 10, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  featureIconPink: { width: 42, height: 42, marginBottom: 10, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  featureKicker: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 0.8, color: '#8051C8' },
  featureKickerPink: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 0.8, color: '#D64D82' },
  featureTitle: { marginTop: 4, fontFamily: 'Jua', fontSize: 15, color: '#43274F' },
  featureText: { marginTop: 5, fontSize: 10, lineHeight: 15, color: '#786C7C' },
  primaryAction: { marginTop: 12, minHeight: 61, paddingHorizontal: 12, borderRadius: 20, backgroundColor: '#8051C8', flexDirection: 'row', alignItems: 'center', gap: 10, shadowColor: '#603495', shadowOpacity: 0.2, shadowRadius: 11, shadowOffset: { width: 0, height: 5 }, elevation: 5 },
  primaryActionIcon: { width: 39, height: 39, borderRadius: 13, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  primaryActionCopy: { flex: 1 },
  primaryActionLabel: { fontFamily: 'Jua', fontSize: 8, letterSpacing: 0.9, color: '#DCC9EE' },
  primaryActionText: { marginTop: 2, fontFamily: 'Jua', fontSize: 14, color: '#FFFFFF' },
  emptyCard: { marginTop: 14, padding: 23, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.97)', borderWidth: 1, borderColor: '#EEE6F1', alignItems: 'center' },
  emptyIcon: { width: 50, height: 50, borderRadius: 17, backgroundColor: '#F3EAF9', alignItems: 'center', justifyContent: 'center' },
  emptyTitle: { marginTop: 11, fontFamily: 'Jua', fontSize: 18, color: '#452A52' },
  emptyCopy: { marginTop: 5, maxWidth: 390, textAlign: 'center', fontSize: 12, lineHeight: 18, color: '#817583' },
  dataCard: { marginTop: 14, padding: 17, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.97)', borderWidth: 1, borderColor: '#EEE6F1' },
  dataTitle: { marginBottom: 11, fontFamily: 'Jua', fontSize: 18, color: '#452A52' },
  noteRow: { marginTop: 8, padding: 11, borderRadius: 16, backgroundColor: '#F9F4FC', flexDirection: 'row', alignItems: 'center' },
  noteNumber: { width: 28, height: 28, borderRadius: 10, backgroundColor: '#8051C8', alignItems: 'center', justifyContent: 'center', marginRight: 9 },
  noteNumberText: { fontFamily: 'Jua', fontSize: 11, color: '#FFFFFF' },
  noteText: { flex: 1, fontSize: 12, lineHeight: 17, color: '#625666' },
  historyRow: { minHeight: 56, borderBottomWidth: 1, borderBottomColor: '#EEE7F1', flexDirection: 'row', alignItems: 'center' },
  historyIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#F3EAF9', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  historyTitle: { flex: 1, fontFamily: 'Jua', fontSize: 13, color: '#4D3458' },
  historyScore: { fontFamily: 'Jua', fontSize: 14, color: '#6AB53B' },
  progressLink: { marginTop: 14, padding: 14, borderRadius: 22, backgroundColor: '#F0F8EA', borderWidth: 1, borderColor: '#CFE5C1', flexDirection: 'row', alignItems: 'center' },
  progressIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', marginRight: 11 },
  progressCopy: { flex: 1 },
  progressTitle: { fontFamily: 'Jua', fontSize: 14, color: '#3D5D2C' },
  progressText: { marginTop: 2, fontSize: 10, lineHeight: 15, color: '#718268' },
});
