import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FBF9FD' },
  container: { flex: 1, overflow: 'hidden', backgroundColor: '#FBF9FD' },
  scrollView: { flex: 1, width: '100%' },
  content: { width: '100%', maxWidth: 620, minHeight: '100%', alignSelf: 'center', paddingHorizontal: 24, paddingTop: 24, paddingBottom: 22 },
  decorativeCircle: { position: 'absolute', width: 410, height: 410, borderRadius: 205, right: -205, top: 96, backgroundColor: '#F0E2FA' },
  decorativeCircleSmall: { position: 'absolute', width: 190, height: 190, borderRadius: 95, left: -118, bottom: 36, backgroundColor: '#EAF5E3' },
  cloudOne: { position: 'absolute', width: 94, height: 18, borderRadius: 20, right: 22, top: 174, backgroundColor: 'rgba(255,255,255,.78)' },
  cloudTwo: { position: 'absolute', width: 62, height: 14, borderRadius: 18, right: 116, top: 206, backgroundColor: 'rgba(255,255,255,.72)' },
  brandRow: { flexDirection: 'row', alignItems: 'center' },
  logoPlate: { width: 54, height: 54, borderRadius: 17, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center', marginRight: 12, shadowColor: '#5D168F', shadowOpacity: .2, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  appLogo: { width: 44, height: 44, borderRadius: 13 },
  brandName: { color: '#2E193C', fontSize: 20, fontWeight: '900', letterSpacing: .8 },
  brandSubtitle: { color: '#75667D', fontSize: 10, marginTop: 2 },
  hero: { minHeight: 390, justifyContent: 'center', paddingTop: 18 },
  heroCopy: { width: '63%', zIndex: 3 },
  eyebrowPill: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, height: 27, borderRadius: 99, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E9DDF0' },
  eyebrowDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6, backgroundColor: '#65A936' },
  eyebrow: { color: '#684A75', fontSize: 7, fontWeight: '900', letterSpacing: 1 },
  title: { color: '#342040', fontFamily: 'Jua', fontSize: 35, lineHeight: 42, marginTop: 15 },
  subtitle: { color: '#776A7C', fontSize: 12, lineHeight: 19, marginTop: 11, maxWidth: 330 },
  mascotScene: { position: 'absolute', width: 250, height: 300, right: -28, bottom: 12, alignItems: 'center', justifyContent: 'flex-end' },
  mascotHalo: { position: 'absolute', width: 220, height: 220, borderRadius: 110, bottom: 15, backgroundColor: 'rgba(224,196,246,.68)', borderWidth: 1, borderColor: 'rgba(255,255,255,.7)' },
  mascot: { width: 184, height: 222, zIndex: 3, marginBottom: 7 },
  mascotGround: { position: 'absolute', width: 182, height: 22, borderRadius: 12, bottom: 0, backgroundColor: 'rgba(132,35,217,.12)' },
  toriiTop: { position: 'absolute', width: 145, height: 9, borderRadius: 6, left: 2, bottom: 69, backgroundColor: 'rgba(132,35,217,.09)' },
  toriiLeft: { position: 'absolute', width: 8, height: 83, left: 25, bottom: 2, backgroundColor: 'rgba(132,35,217,.09)' },
  toriiRight: { position: 'absolute', width: 8, height: 83, left: 113, bottom: 2, backgroundColor: 'rgba(132,35,217,.09)' },
  speechBubble: { position: 'absolute', right: 4, top: 24, minWidth: 91, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 16, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E8DCEF', shadowColor: '#4B2D58', shadowOpacity: .09, shadowRadius: 8, elevation: 2, zIndex: 5 },
  speechJapanese: { color: '#8423D9', fontSize: 12, fontWeight: '800', textAlign: 'center' },
  speechTranslation: { color: '#887A8D', fontSize: 7, textAlign: 'center', marginTop: 2 },
  featureRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', borderRadius: 23, paddingHorizontal: 12, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E9E1ED', shadowColor: '#472553', shadowOpacity: .06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 },
  featureItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  featureIcon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  featureIconPurple: { backgroundColor: '#F0E3FA' },
  featureIconGreen: { backgroundColor: '#EAF5E3' },
  featureIconOrange: { backgroundColor: '#FFF0DC' },
  featureText: { color: '#5D4C65', fontSize: 8, fontWeight: '700', marginTop: 5, textAlign: 'center' },
  featureDivider: { width: 1, height: 38, backgroundColor: '#EEE7F1' },
  actions: { marginTop: 17, gap: 10 },
  primaryButton: { height: 58, borderRadius: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#8423D9', borderBottomWidth: 5, borderBottomColor: '#6515A8', shadowColor: '#6420A0', shadowOpacity: .2, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  primaryButtonText: { color: '#FFF', fontFamily: 'Jua', fontSize: 17 },
  primaryArrow: { position: 'absolute', right: 12, width: 35, height: 35, borderRadius: 12, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  secondaryButton: { height: 54, borderRadius: 18, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#DDD0E4' },
  secondaryButtonText: { color: '#593F66', fontFamily: 'Jua', fontSize: 14 },
  buttonPressed: { opacity: .82, transform: [{ scale: .99 }] },
  footerText: { color: '#9A8EA0', fontSize: 8, textAlign: 'center', marginTop: 13 },
});

export default styles;
