import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, minHeight: 0, backgroundColor: '#FBF9FD', overflow: 'hidden' },
    scrollView: { flex: 1 },
    darkContainer: { backgroundColor: '#17111D' },
    scrollContent: { paddingBottom: 112 },
    hero: {
        backgroundColor: '#8423D9', minHeight: 310, alignItems: 'center',
        paddingHorizontal: 20, paddingBottom: 34, overflow: 'hidden',
        borderBottomLeftRadius: 34, borderBottomRightRadius: 34,
    },
    heroCircleOne: {
        position: 'absolute', width: 230, height: 230, borderRadius: 115,
        backgroundColor: 'rgba(255,255,255,0.07)', top: -100, right: -60,
    },
    heroCircleTwo: {
        position: 'absolute', width: 155, height: 155, borderRadius: 80,
        backgroundColor: 'rgba(142,217,77,0.10)', bottom: -70, left: -45,
    },
    header: {
        width: '100%', height: 68, flexDirection: 'row', alignItems: 'center',
        justifyContent: 'space-between', marginBottom: 10,
    },
    iconButton: {
        width: 42, height: 42, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center', justifyContent: 'center',
    },
    headerTitle: { color: '#FFFFFF', fontFamily: 'Jua', fontSize: 21 },
    headerSpacer: { width: 42 },
    avatarShell: {
        width: 112, height: 112, borderRadius: 34, backgroundColor: '#FFFFFF',
        padding: 5, alignItems: 'center', justifyContent: 'center',
        shadowColor: '#30143F', shadowOpacity: 0.28, shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 }, elevation: 8,
    },
    profilePicture: { width: 100, height: 100, borderRadius: 29, resizeMode: 'cover' },
    studentBadge: {
        position: 'absolute', right: -7, bottom: -7, width: 34, height: 34,
        borderRadius: 12, backgroundColor: '#8ED94D', borderWidth: 3, borderColor: '#8423D9',
        alignItems: 'center', justifyContent: 'center',
    },
    profileName: { color: '#FFFFFF', fontFamily: 'Jua', fontSize: 24, marginTop: 15 },
    rolePill: {
        backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 99,
        paddingHorizontal: 12, paddingVertical: 6, marginTop: 7,
    },
    roleText: { color: '#F2E7FA', fontSize: 10, fontWeight: '800', letterSpacing: 1.1 },

    pageContent: { paddingHorizontal: 20, marginTop: 20 },
    infoCard: {
        backgroundColor: '#FFFFFF', borderRadius: 23, padding: 18,
        borderWidth: 1, borderColor: '#EEE7F1',
        shadowColor: '#462A5E', shadowOpacity: 0.09, shadowRadius: 14,
        shadowOffset: { width: 0, height: 5 }, elevation: 4,
    },
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 },
    sectionTitle: { color: '#462A5E', fontFamily: 'Jua', fontSize: 19 },
    sectionSubtitle: { color: '#8B808F', fontSize: 11, marginTop: 2 },
    verifiedPill: {
        flexDirection: 'row', alignItems: 'center', gap: 4,
        backgroundColor: '#EDF8E5', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 99,
    },
    verifiedText: { color: '#4C8C20', fontWeight: '700', fontSize: 10 },
    infoRow: {
        flexDirection: 'row', alignItems: 'center', paddingVertical: 12,
        borderBottomWidth: 1, borderBottomColor: '#F1EDF3',
    },
    lastInfoRow: { borderBottomWidth: 0, paddingBottom: 2 },
    infoIcon: {
        width: 42, height: 42, borderRadius: 14, backgroundColor: '#F0E4FA',
        alignItems: 'center', justifyContent: 'center', marginRight: 12,
    },
    infoCopy: { flex: 1 },
    infoLabel: { color: '#9B929F', fontSize: 11, fontWeight: '600' },
    infoValue: { color: '#4C3B55', fontSize: 14, fontWeight: '700', marginTop: 3 },
    classInfoRow: { alignItems: 'flex-start', paddingTop: 14 },
    classInfoCopy: { flex: 1 },
    classJoinRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 7 },
    classCodeInput: {
        flex: 1, minWidth: 0, height: 43, borderRadius: 13,
        borderWidth: 1, borderColor: '#E3D8EA', backgroundColor: '#FAF7FC',
        color: '#4C3B55', fontSize: 13, fontWeight: '700', paddingHorizontal: 12,
        outlineStyle: 'none',
    },
    darkClassCodeInput: { backgroundColor: '#211827', borderColor: '#4A3955' },
    joinClassButton: {
        minWidth: 66, height: 43, borderRadius: 13, backgroundColor: '#8423D9',
        alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12,
    },
    joinClassButtonDisabled: { opacity: 0.5 },
    joinClassButtonText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800', letterSpacing: 0.7 },
    classHelpText: { color: '#978D9B', fontSize: 10, marginTop: 6 },

    achievementsCard: {
        backgroundColor: '#FFFFFF', borderRadius: 23, padding: 18, marginTop: 15,
        borderWidth: 1, borderColor: '#EEE7F1',
        shadowColor: '#462A5E', shadowOpacity: 0.07, shadowRadius: 12,
        shadowOffset: { width: 0, height: 5 }, elevation: 3,
    },
    badgeContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    badgeWrapper: { width: '31%', alignItems: 'center' },
    badgeImageShell: {
        width: 82, height: 82, borderRadius: 23, backgroundColor: '#F4F1F5',
        alignItems: 'center', justifyContent: 'center', position: 'relative',
    },
    badgeAcquired: { backgroundColor: '#F1F9EA', borderWidth: 1, borderColor: '#D7EDC6' },
    badgeImage: { width: 74, height: 68, resizeMode: 'contain' },
    badgeStatus: {
        position: 'absolute', right: -4, bottom: -4, width: 23, height: 23,
        borderRadius: 8, alignItems: 'center', justifyContent: 'center',
        borderWidth: 2, borderColor: '#FFFFFF',
    },
    badgeStatusUnlocked: { backgroundColor: '#73BE3E' },
    badgeStatusLocked: { backgroundColor: '#9F969F' },
    badgeName: { color: '#62546A', fontSize: 11, fontWeight: '700', textAlign: 'center', marginTop: 9 },

    settingsTitle: { color: '#462A5E', fontFamily: 'Jua', fontSize: 18, marginTop: 22, marginBottom: 10 },
    settingsCard: {
        backgroundColor: '#FFFFFF', borderRadius: 21, paddingHorizontal: 16,
        borderWidth: 1, borderColor: '#EEE7F1', overflow: 'hidden',
    },
    settingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#F0EBF2' },
    logoutRow: { borderBottomWidth: 0 },
    settingIcon: {
        width: 42, height: 42, borderRadius: 14, backgroundColor: '#F0E4FA',
        alignItems: 'center', justifyContent: 'center', marginRight: 12,
    },
    logoutIcon: { backgroundColor: '#FCEBED' },
    settingCopy: { flex: 1 },
    settingLabel: { color: '#4C3B55', fontSize: 14, fontWeight: '700' },
    logoutLabel: { color: '#B73540', fontSize: 14, fontWeight: '700' },
    settingDescription: { color: '#978D9B', fontSize: 11, marginTop: 3 },

    modalContainer: {
        flex: 1, justifyContent: 'center', alignItems: 'center',
        backgroundColor: 'rgba(38,22,50,0.58)', paddingHorizontal: 24,
    },
    modalContent: {
        width: '100%', maxWidth: 380, backgroundColor: '#FFFFFF', borderRadius: 24,
        padding: 25, alignItems: 'center',
        shadowColor: '#24152F', shadowOpacity: 0.25, shadowRadius: 22,
        shadowOffset: { width: 0, height: 10 }, elevation: 10,
    },
    modalIcon: {
        width: 58, height: 58, borderRadius: 19, backgroundColor: '#F0E4FA',
        alignItems: 'center', justifyContent: 'center', marginBottom: 14,
    },
    modalTitle: { color: '#462A5E', fontFamily: 'Jua', fontSize: 21, textAlign: 'center' },
    modalMessage: { color: '#756A7B', fontSize: 14, lineHeight: 21, textAlign: 'center', marginVertical: 12 },
    buttonContainer: {
        width: '100%', height: 52, backgroundColor: '#8ED94D', borderRadius: 15,
        justifyContent: 'center', marginTop: 8, borderBottomWidth: 5, borderBottomColor: '#73B83B',
    },
    buttonText: { color: '#FFFFFF', fontFamily: 'Jua', fontSize: 16, textAlign: 'center' },
    darkCard: { backgroundColor: '#281E30', borderColor: '#3D3046' },
    darkTitle: { color: '#F5EDF9' },
    darkText: { color: '#EDE4F1' },
    darkMuted: { color: '#B6A9BC' },
});
