import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  background: { flex: 1, backgroundColor: '#FBF8FF' },
  scrollContent: { paddingBottom: 50 },
  hero: { minHeight: 310, paddingHorizontal: 24, paddingTop: 48, paddingBottom: 25, overflow: 'hidden' },
  heroCompact: { minHeight: 332, paddingHorizontal: 18 },
  heroOrb: { position: 'absolute', width: 300, height: 300, borderRadius: 150, right: -82, top: 12, backgroundColor: '#EAD7FA' },
  heroOrbInner: { position: 'absolute', width: 205, height: 205, borderRadius: 103, right: -34, top: 65, backgroundColor: '#DFC0F6' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 2 },
  backButton: { width: 52, height: 52, borderRadius: 17, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#EADDF1', alignItems: 'center', justifyContent: 'center', elevation: 4, shadowColor: '#422052', shadowOpacity: 0.1, shadowRadius: 10 },
  journeyLabel: { color: '#4E2B60', fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  bookButton: { width: 52, height: 52, borderRadius: 17, backgroundColor: '#EEE0FB', alignItems: 'center', justifyContent: 'center' },
  heroCopy: { width: '57%', marginTop: 62, zIndex: 2 },
  heroCopyCompact: { width: '51%', marginTop: 50 },
  eyebrow: { color: '#64B936', fontSize: 9, fontWeight: '900', letterSpacing: 1.4, marginBottom: 7 },
  title: { color: '#372044', fontFamily: 'Jua', fontWeight: '400', fontSize: 29, lineHeight: 36, marginBottom: 9 },
  titleCompact: { fontSize: 23, lineHeight: 28 },
  subtitle: { color: '#736678', fontSize: 14, lineHeight: 21 },
  subtitleCompact: { fontSize: 11, lineHeight: 17 },
  collage: { position: 'absolute', right: 3, bottom: 2, width: 218, height: 205 },
  collageCompact: { right: -7, bottom: 6, width: 178, height: 184 },
  coverPlate: { position: 'absolute', right: 11, bottom: 8, width: 176, height: 160, borderRadius: 44, backgroundColor: 'rgba(255,255,255,0.56)', transform: [{ rotate: '-4deg' }] },
  coverPlateCompact: { width: 145, height: 140, right: 8 },
  collageImageMain: { position: 'absolute', width: 148, height: 137, resizeMode: 'cover', right: -1, bottom: 1, backgroundColor: '#EEE1F8', borderRadius: 31, borderWidth: 4, borderColor: '#FFFFFF' },
  collageImageMainCompact: { width: 120, height: 122, right: 0, borderRadius: 25 },
  collageImageSmall: { position: 'absolute', width: 96, height: 92, resizeMode: 'cover', left: -1, top: 31, backgroundColor: '#FFF', borderRadius: 26, borderWidth: 4, borderColor: '#FFF', transform: [{ rotate: '-6deg' }] },
  collageImageSmallCompact: { width: 76, height: 75, left: 2, top: 43, borderRadius: 21 },
  collageImageAccent: { position: 'absolute', width: 75, height: 72, resizeMode: 'cover', right: 2, top: 1, backgroundColor: '#F2E8FA', borderRadius: 21, borderWidth: 4, borderColor: '#FFF', transform: [{ rotate: '5deg' }] },
  collageImageAccentCompact: { width: 62, height: 61, right: 1, top: 17, borderRadius: 18 },
  wordBubble: { position: 'absolute', right: 78, top: 4, backgroundColor: '#FFF', borderRadius: 15, paddingHorizontal: 12, paddingVertical: 7, elevation: 3 },
  wordBubbleCompact: { right: 62, top: 16, paddingHorizontal: 9, paddingVertical: 6 },
  wordBubbleText: { color: '#8423D9', fontFamily: 'Jua', fontSize: 13 },
  body: { width: '100%', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 24 },
  sectionHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 18 },
  sectionTitle: { color: '#432752', fontFamily: 'Jua', fontWeight: '400', fontSize: 24 },
  sectionSubtitle: { color: '#8A7D8E', fontSize: 13, marginTop: 4 },
  countPill: { backgroundColor: '#EAF5E4', borderRadius: 18, paddingHorizontal: 13, paddingVertical: 8 },
  countText: { color: '#55A72E', fontSize: 9, fontWeight: '900', letterSpacing: 0.7 },
  setCard: { width: '100%', height: 184, minHeight: 184, borderRadius: 27, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E9DDED', marginBottom: 16, overflow: 'hidden', flexDirection: 'row', shadowColor: '#432451', shadowOpacity: 0.07, shadowRadius: 15, shadowOffset: { width: 0, height: 7 }, elevation: 3 },
  setCardLocked: { opacity: 0.62 },
  imagePanel: { width: 132, height: '100%', flexShrink: 0, backgroundColor: '#F0E1FC', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  imagePanelGreen: { backgroundColor: '#EAF5E2' },
  cardImage: { ...StyleSheet.absoluteFillObject, width: undefined, height: undefined },
  cardCharacter: { display: 'none' },
  cardContent: { flex: 1, minWidth: 0, padding: 18, justifyContent: 'center' },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 },
  status: { color: '#8423D9', fontSize: 8, fontWeight: '900', letterSpacing: 1.1 },
  statusDone: { color: '#58AD30' },
  cardTitle: { color: '#442651', fontFamily: 'Jua', fontWeight: '400', fontSize: 20, marginBottom: 4 },
  cardCopy: { color: '#827687', fontSize: 13, lineHeight: 19, marginBottom: 14 },
  cardAction: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  cardActionText: { color: '#8423D9', fontSize: 11, fontWeight: '800' },
  cardActionGreen: { color: '#57AA31' },
  reviewCard: { width: '100%', height: 174, minHeight: 174, borderRadius: 28, padding: 15, backgroundColor: '#FFFFFF', overflow: 'hidden', flexDirection: 'row', alignItems: 'stretch', borderWidth: 1, borderColor: '#DFD0E8', shadowColor: '#42234F', shadowOpacity: 0.1, shadowRadius: 17, shadowOffset: { width: 0, height: 8 }, elevation: 4 },
  reviewCardLocked: { opacity: 0.62, backgroundColor: '#F8F5FA' },
  reviewGlow: { position: 'absolute', width: 190, height: 190, borderRadius: 95, backgroundColor: '#F1E3FC', left: -72, bottom: -80 },
  reviewArtwork: { width: 132, minHeight: 142, marginRight: 15, justifyContent: 'center' },
  reviewPhoto: { position: 'absolute', width: 82, height: 94, borderRadius: 20, backgroundColor: '#EFE3F8', borderWidth: 3, borderColor: '#FFFFFF', overflow: 'hidden', shadowColor: '#432451', shadowOpacity: 0.12, shadowRadius: 6, elevation: 2 },
  reviewPhotoImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  reviewPhotoBack: { left: 42, top: 12, transform: [{ rotate: '8deg' }] },
  reviewPhotoMiddle: { left: 6, top: 26, transform: [{ rotate: '-9deg' }] },
  reviewPhotoFront: { left: 28, top: 46 },
  reviewSpark: { position: 'absolute', width: 38, height: 38, borderRadius: 13, backgroundColor: '#8423D9', right: 1, bottom: 4, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: '#FFFFFF' },
  reviewContent: { flex: 1, paddingVertical: 4, justifyContent: 'center' },
  reviewTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 7 },
  reviewEyebrow: { flex: 1, color: '#8423D9', fontSize: 7, fontWeight: '900', letterSpacing: 0.8 },
  reviewStatus: { borderRadius: 10, backgroundColor: '#EEE9F0', paddingHorizontal: 7, paddingVertical: 4 },
  reviewStatusReady: { backgroundColor: '#EAF6E3' },
  reviewStatusText: { color: '#8D8391', fontSize: 6, fontWeight: '900' },
  reviewStatusTextReady: { color: '#579D32' },
  reviewTitle: { color: '#43254F', fontFamily: 'Jua', fontWeight: '400', fontSize: 20 },
  reviewCopy: { color: '#7E7184', fontSize: 10, lineHeight: 15, marginTop: 3 },
  reviewAction: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 13 },
  reviewActionText: { color: '#8423D9', fontSize: 10, fontWeight: '900' },
  reviewArrow: { width: 30, height: 30, borderRadius: 11, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center' },
  awardModal: { flex: 1, backgroundColor: 'rgba(37,18,48,0.58)', padding: 25, alignItems: 'center', justifyContent: 'center' },
  awardCard: { width: '100%', maxWidth: 390, backgroundColor: '#FFF', borderRadius: 32, padding: 27, alignItems: 'center' },
  awardGlow: { width: 114, height: 114, borderRadius: 57, backgroundColor: '#F0E0FB', alignItems: 'center', justifyContent: 'center', marginBottom: 18 },
  awardBadge: { width: 88, height: 88, resizeMode: 'contain' },
  awardEyebrow: { color: '#61B536', fontSize: 9, fontWeight: '900', letterSpacing: 1.1, marginBottom: 8 },
  awardTitle: { color: '#3D234A', fontFamily: 'Jua', fontWeight: '400', fontSize: 25, textAlign: 'center' },
  awardCopy: { color: '#7B6F80', fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 9, marginBottom: 21 },
  awardButton: { width: '100%', minHeight: 55, borderRadius: 18, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center' },
  awardButtonText: { color: '#FFF', fontSize: 13, fontWeight: '900' },
});
