import { StyleSheet } from 'react-native';
export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FAF7FD', paddingHorizontal: 20, paddingTop: 46, paddingBottom: 22 },
  ambientTop: { position: 'absolute', width: 310, height: 310, borderRadius: 155, backgroundColor: '#EFDFFC', right: -145, top: -145 },
  ambientBottom: { position: 'absolute', width: 180, height: 180, borderRadius: 90, backgroundColor: '#EDF7E7', left: -95, bottom: -75 },
  topRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 }, backButton: { width: 52, height: 52, borderRadius: 17, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E7DAED', alignItems: 'center', justifyContent: 'center', shadowColor: '#452452', shadowOpacity: 0.09, shadowRadius: 10, elevation: 3 }, headerCopy: { flex: 1, marginLeft: 14 }, topEyebrow: { color: '#68B63D', fontSize: 8, fontWeight: '900', letterSpacing: 1.3 }, topLabel: { color: '#3F244C', fontFamily: 'Jua', fontSize: 21, marginTop: 2 }, countPill: { borderRadius: 17, backgroundColor: '#EFE2F9', paddingHorizontal: 12, paddingVertical: 8 }, topCount: { color: '#8423D9', fontSize: 9, fontWeight: '900' },
  progress: { height: 7, borderRadius: 7, backgroundColor: '#E9E1EC', overflow: 'hidden', marginBottom: 16 }, progressFill: { height: '100%', borderRadius: 7, backgroundColor: '#8423D9' },
  quizCard: { flex: 1, backgroundColor: '#FFF', borderRadius: 32, borderWidth: 1, borderColor: '#E6D9EC', padding: 14, alignItems: 'center', shadowColor: '#422451', shadowOpacity: 0.11, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 5 },
  questionHead: { width: '100%', paddingHorizontal: 9, paddingTop: 6, paddingBottom: 12 }, questionTag: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 14, backgroundColor: '#F1E5FA', paddingHorizontal: 10, paddingVertical: 6 }, questionTagText: { color: '#8423D9', fontSize: 8, fontWeight: '900', letterSpacing: 0.8 }, prompt: { color: '#432550', fontFamily: 'Jua', fontWeight: '400', fontSize: 21, lineHeight: 27, marginTop: 10 },
  imageStage: { width: '100%', flex: 1, minHeight: 215, maxHeight: 315, borderRadius: 25, backgroundColor: '#F1E5FA', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 1, borderColor: '#E4D2F0' }, image: { width: '100%', height: '100%', resizeMode: 'cover' },
  hintRow: { alignSelf: 'stretch', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginVertical: 11 }, hintLabel: { color: '#8B7E90', fontSize: 10, fontWeight: '700' }, hint: { color: '#59A932', fontFamily: 'Jua', fontSize: 16 },
  choices: { width: '100%', gap: 8 }, choice: { minHeight: 51, borderRadius: 16, backgroundColor: '#F7F2F9', borderWidth: 1, borderColor: '#E7DCEA', paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, choiceText: { color: '#4E305B', fontFamily: 'Jua', fontSize: 18 }, correct: { backgroundColor: '#62B936', borderColor: '#62B936' }, wrong: { backgroundColor: '#D95A72', borderColor: '#D95A72' }, selectedText: { color: '#FFF' }, helper: { color: '#988C9B', fontSize: 11, marginTop: 13 },
  feedback: { width: '100%', borderRadius: 15, paddingHorizontal: 13, paddingVertical: 9, marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, feedbackCorrect: { backgroundColor: '#EDF8E8' }, feedbackWrong: { backgroundColor: '#FCECF0' }, feedbackText: { flex: 1, fontSize: 12, fontWeight: '800' }, feedbackTextCorrect: { color: '#4C9929' }, feedbackTextWrong: { color: '#C34F66' },
  primaryButton: { width: '100%', minHeight: 54, borderRadius: 17, marginTop: 11, backgroundColor: '#8423D9', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, primaryText: { color: '#FFF', fontSize: 13, fontWeight: '900' },
  resultCard: { marginTop: '18%', backgroundColor: '#FFF', borderRadius: 34, borderWidth: 1, borderColor: '#E6D8ED', padding: 27, alignItems: 'center', shadowColor: '#432451', shadowOpacity: 0.12, shadowRadius: 20, elevation: 5 }, resultIcon: { width: 96, height: 96, borderRadius: 31, backgroundColor: '#EFE0FB', alignItems: 'center', justifyContent: 'center', marginBottom: 17 }, eyebrow: { color: '#62B636', fontSize: 9, fontWeight: '900', letterSpacing: 1.2 }, resultTitle: { color: '#40244C', fontFamily: 'Jua', fontWeight: '400', fontSize: 27, textAlign: 'center', marginTop: 7 }, scorePanel: { width: '100%', backgroundColor: '#F6F0F9', borderRadius: 21, alignItems: 'center', paddingVertical: 14, marginVertical: 14 }, scoreLabel: { color: '#8B7E90', fontSize: 10, fontWeight: '800' }, score: { color: '#8423D9', fontFamily: 'Jua', fontSize: 38, lineHeight: 45 }, resultCopy: { color: '#7D7182', fontSize: 14, lineHeight: 21, textAlign: 'center' }, replayButton: { paddingVertical: 14 }, replayText: { color: '#663577', fontSize: 12, fontWeight: '900' }
});
