import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FBF9FD' },
  container: { flex: 1, overflow: 'hidden', backgroundColor: '#FBF9FD' },
  keyboardView: { flex: 1 },
  scrollContent: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 20, paddingVertical: 24 },
  backgroundOrbTop: { position: 'absolute', width: 430, height: 430, borderRadius: 215, backgroundColor: '#EFE0FA', top: -230, right: -180 },
  backgroundOrbBottom: { position: 'absolute', width: 310, height: 310, borderRadius: 155, backgroundColor: '#E8F5DE', bottom: -175, left: -145 },
  backgroundSpark: { position: 'absolute', width: 18, height: 18, borderRadius: 6, backgroundColor: '#A8E16E', top: '15%', left: '8%', transform: [{ rotate: '45deg' }] },
  loginShell: { width: '100%', maxWidth: 1040, alignSelf: 'center', gap: 16 },
  loginShellWide: { minHeight: 650, flexDirection: 'row', alignItems: 'stretch', gap: 0, borderRadius: 34, overflow: 'hidden', backgroundColor: '#FFFFFF', shadowColor: '#3B1A50', shadowOpacity: 0.14, shadowRadius: 34, shadowOffset: { width: 0, height: 16 }, elevation: 10 },
  welcomePanel: { minHeight: 340, borderRadius: 28, padding: 22, overflow: 'hidden', backgroundColor: '#F2E6FA', borderWidth: 1, borderColor: '#E6D3F2' },
  welcomePanelWide: { width: '50%', minHeight: 650, borderRadius: 0, borderWidth: 0, padding: 34, justifyContent: 'space-between' },
  brandRow: { flexDirection: 'row', alignItems: 'center', zIndex: 3 },
  logoPlate: { width: 50, height: 50, borderRadius: 16, backgroundColor: '#8423D9', alignItems: 'center', justifyContent: 'center', marginRight: 11, shadowColor: '#5D168F', shadowOpacity: 0.2, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  appLogo: { width: 41, height: 41, borderRadius: 12 },
  brandName: { color: '#2E193C', fontSize: 19, fontWeight: '900', letterSpacing: 0.8 },
  brandSubtitle: { color: '#75667D', fontSize: 10, marginTop: 2 },
  mascotScene: { height: 190, alignItems: 'center', justifyContent: 'flex-end', marginTop: 8 },
  mascotSceneWide: { height: 310, marginVertical: 10 },
  mascotHalo: { position: 'absolute', width: 230, height: 230, borderRadius: 115, bottom: -25, backgroundColor: 'rgba(255,255,255,0.52)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.8)' },
  mascotGround: { position: 'absolute', width: 180, height: 18, borderRadius: 10, bottom: 0, backgroundColor: 'rgba(132,35,217,0.12)' },
  mascot: { width: 150, height: 180, zIndex: 2, marginBottom: 3 },
  speechCard: { position: 'absolute', right: 3, top: 8, zIndex: 4, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 16, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E5D5ED', shadowColor: '#4E2564', shadowOpacity: 0.1, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
  speechJapanese: { color: '#7020C7', fontSize: 13, fontWeight: '800' },
  speechEnglish: { color: '#8B7D91', fontSize: 9, marginTop: 2 },
  welcomeCopy: { alignItems: 'center', zIndex: 3, marginTop: 16 },
  welcomeEyebrow: { color: '#65A936', fontSize: 10, fontWeight: '900', letterSpacing: 1.6 },
  welcomeTitle: { maxWidth: 390, color: '#342040', fontFamily: 'Jua', fontSize: 28, lineHeight: 35, marginTop: 8, textAlign: 'center' },
  welcomeText: { maxWidth: 390, color: '#75697B', fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: 'center' },
  formCard: { width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: '#FFFFFF', borderRadius: 28, padding: 24, borderWidth: 1, borderColor: '#EAE2EE', shadowColor: '#462A5E', shadowOpacity: 0.1, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 6 },
  formCardWide: { width: '50%', maxWidth: undefined, borderRadius: 0, borderWidth: 0, paddingHorizontal: 52, paddingVertical: 44, justifyContent: 'center', shadowOpacity: 0, elevation: 0 },
  studentBadge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 999, backgroundColor: '#EFF8E8', marginBottom: 14 },
  studentBadgeText: { color: '#5B9630', fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  formTitle: { fontFamily: 'Jua', fontSize: 31, lineHeight: 38, color: '#342040' },
  formSubtitle: { color: '#817586', fontSize: 14, lineHeight: 21, marginTop: 3, marginBottom: 24 },
  fieldLabel: { color: '#4B3656', fontSize: 12, fontWeight: '800', marginBottom: 8 },
  passwordLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 },
  forgotLink: { color: '#7A25C8', fontSize: 12, fontWeight: '700', marginBottom: 8 },
  inputContainer: { height: 58, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAF8FB', borderWidth: 1.5, borderColor: '#E5DDE9', borderRadius: 17, paddingHorizontal: 10, marginBottom: 17 },
  passwordContainer: { height: 58, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAF8FB', borderWidth: 1.5, borderColor: '#E5DDE9', borderRadius: 17, paddingHorizontal: 10, position: 'relative' },
  inputContainerFocused: { borderColor: '#8A2CDF', backgroundColor: '#FDFBFF', shadowColor: '#8423D9', shadowOpacity: 0.1, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 2 },
  inputIconWrap: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#F0E3FA', alignItems: 'center', justifyContent: 'center' },
  input: { flex: 1, color: '#3D2947', paddingHorizontal: 11, height: 56, fontSize: 15, outlineStyle: 'none', outlineWidth: 0 },
  passwordInput: { paddingRight: 42 },
  insideInputButton: { position: 'absolute', right: 8, height: '100%', width: 40, justifyContent: 'center', alignItems: 'center' },
  buttonContainer: { marginTop: 20 },
  button: { height: 60, width: '100%', borderRadius: 18, backgroundColor: '#8423D9', borderBottomWidth: 5, borderBottomColor: '#6515A8', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, shadowColor: '#6420A0', shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 5 },
  buttonPressed: { opacity: 0.84, transform: [{ scale: 0.99 }] },
  buttonDisabled: { opacity: 0.72 },
  buttonText: { color: '#FFFFFF', fontSize: 17, fontFamily: 'Jua' },
  buttonArrow: { position: 'absolute', right: 12, width: 36, height: 36, borderRadius: 12, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  signupDivider: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 20 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#EAE2EE' },
  dividerText: { color: '#9A8DA0', fontSize: 9, fontWeight: '800', letterSpacing: 1.1 },
  createButton: { height: 54, borderRadius: 17, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8F3FB', borderWidth: 1, borderColor: '#DFD0E7' },
  createButtonText: { color: '#60406F', fontFamily: 'Jua', fontSize: 14 },
  policyTextContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap', marginTop: 19, paddingHorizontal: 4 },
  policyText: { fontSize: 10, lineHeight: 16, color: '#918496', textAlign: 'center' },
  linkText2: { fontSize: 10, lineHeight: 16, color: '#7623C6', fontWeight: '700' },
  inputReset: { flex: 1, color: '#462A5E', paddingHorizontal: 10, height: 56, fontSize: 16, outlineStyle: 'none', outlineWidth: 0 },
  modalContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(38,22,50,0.58)', paddingHorizontal: 22 },
  modalContent: { justifyContent: 'center', alignItems: 'center', padding: 27, backgroundColor: '#FFFFFF', borderRadius: 26, width: '100%', maxWidth: 430, shadowColor: '#24152F', shadowOpacity: 0.25, shadowRadius: 24, shadowOffset: { width: 0, height: 12 }, elevation: 12 },
  modalClose: { position: 'absolute', right: 18, top: 18, zIndex: 2, padding: 4 },
  modalIconWrap: { width: 58, height: 58, borderRadius: 18, backgroundColor: '#F0E4FA', alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  modalTitle: { fontFamily: 'Jua', fontSize: 23, marginBottom: 8, textAlign: 'center', color: '#3E294A' },
  modalDescription: { color: '#817586', fontSize: 14, lineHeight: 21, textAlign: 'center', marginBottom: 20 },
  resetInputContainer: { width: '100%', height: 58, flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8F5FA', borderWidth: 1, borderColor: '#E5DDE9', borderRadius: 16, paddingHorizontal: 15, marginBottom: 16 },
  buttonReset: { backgroundColor: '#8423D9', width: '100%', height: 58, borderRadius: 17, borderBottomWidth: 5, borderBottomColor: '#6515A8', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 },
  buttonTextReset: { color: '#FFFFFF', fontSize: 16, fontFamily: 'Jua' },
});

export default styles;
