import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8F3FB' },
  background: { flex: 1 },
  sceneShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(55,32,65,0.18)' },
  topBar: {
    marginHorizontal: 16,
    marginTop: 14,
    padding: 12,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.96)',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#3E234A',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
    zIndex: 4,
  },
  backButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#F7F1FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brand: { flex: 1, marginHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
  brandEyebrow: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.1, color: '#887A8E' },
  brandTitle: { fontFamily: 'Jua', fontSize: 17, color: '#3D234C' },
  roomBadge: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 13, flexDirection: 'row', alignItems: 'center', gap: 5 },
  roomBadgeDot: { width: 6, height: 6, borderRadius: 3 },
  roomBadgeText: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 0.8 },
  roomStage: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', paddingHorizontal: 16, paddingBottom: 18 },
  windowGlow: {
    position: 'absolute',
    top: '7%',
    width: Math.min(width * 0.7, 410),
    aspectRatio: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  coachTag: {
    position: 'absolute',
    top: '6%',
    zIndex: 2,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  coachOnline: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#65B33D' },
  coachTagText: { fontFamily: 'Jua', fontSize: 10, letterSpacing: 0.7, color: '#53325F' },
  sumi: { position: 'absolute', top: '9%', width: Math.min(width * 0.67, 410), height: '49%' },
  characterShadow: {
    position: 'absolute',
    top: '50%',
    width: Math.min(width * 0.48, 280),
    height: 20,
    borderRadius: 999,
    backgroundColor: 'rgba(57,35,61,0.18)',
  },
  infoPanel: {
    width: '100%',
    maxWidth: 520,
    borderRadius: 28,
    padding: 18,
    backgroundColor: 'rgba(255,255,255,0.97)',
    shadowColor: '#3E234A',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  infoTopRow: { flexDirection: 'row', alignItems: 'center' },
  infoIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  infoTitleCopy: { flex: 1 },
  infoKicker: { fontFamily: 'Jua', fontSize: 9, letterSpacing: 1.1 },
  infoTitle: { marginTop: 2, fontFamily: 'Jua', fontSize: 21, color: '#3D234C' },
  infoDescription: { marginTop: 11, fontSize: 13, lineHeight: 19, color: '#746A78' },
  availabilityNote: { marginTop: 12, padding: 11, borderRadius: 15, backgroundColor: '#FFF7E9', flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  availabilityText: { flex: 1, fontSize: 12, lineHeight: 17, color: '#7B603D' },
  microphoneArea: { marginTop: 14, alignItems: 'center' },
  microphoneButton: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: '#FFFFFF',
    shadowColor: '#4B2858',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 7,
  },
  microphonePressed: { transform: [{ scale: 0.96 }] },
  microphoneStatus: { marginTop: 9, textAlign: 'center', fontFamily: 'Jua', fontSize: 13, color: '#4D3358' },
  privacyText: { marginTop: 3, textAlign: 'center', fontSize: 10, color: '#9A8E9E' },
  progressLink: { marginTop: 14, minHeight: 44, borderRadius: 15, backgroundColor: '#F5EEFB', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  progressLinkText: { fontFamily: 'Jua', fontSize: 13, color: '#7552C8' },
});
